DependencyTrack/hyades

- README.md
- src/main/java/org/acme/tasks/scanners/OssIndexAnalysisTask.java
- src/main/java/org/acme/tasks/scanners/SnykAnalysisTask.java
- src/main/resources/application.properties
Passing them via env variables is still possible, see https://quarkus.io/guides/config-reference#environment-variables
Also handle optional values, so it's not required to provide all properties anymore.
> Update scanner configuration to be loadable from properties as well

- src/main/java/org/acme/consumer/OSSIndexBatcher.java
- src/main/java/org/acme/tasks/scanners/BaseComponentAnalyzerTask.java
- src/main/java/org/acme/tasks/scanners/OssIndexAnalysisTask.java
* Emit a `VulnerabilityResult` with `vulnerability=null` when no vulnerabilities have been found
* Emit and cache all reported vulnerabilities, not only one
* Fix caching by setting the `id` field of the generated `Vulnerability`
* Cache results even when no vulnerabilities have been reported by OSS Index
> Fix and improve OSS Index analyzer

- src/main/resources/application.properties
added kafka.bootstrap.servers=localhost:9092 property to enable kafka dev ui to work
Signed-off-by: mehab <meha.bhargava2@gmail.com>
> Fix kafka dev ui on quarkus dev services

- src/main/java/org/acme/consumer/AnalyzerTopology.java
We do not use the project UUID anymore, but instead the component UUID.
> Clarify key of `component-analysis` topic

- src/main/java/org/acme/persistence/CweImporter.java
The relative file path does not resolve when the application is executed outside of the project's root dir, which is the case when deploying it with Docker.
> Load CWE dictionary from classpath

- commons/src/main/resources/alpine.version
- commons/src/main/resources/application.version
- repository-meta-analyzer/src/main/java/org/acme/repositories/MavenMetaAnalyzer.java
The app would fail because the analyzers still use the pooled HTTP client, which rely on Alpine's `Config` for initialization.
Initialization of `Config` would fail because neither `alpine.version` nor `application.version` were on the classpath, causing `NullPointerException`s when the `Config` class was first accessed. 
Also the URL building of the Maven analyzer was broken.
> Fix repo meta analyzer

- commons/pom.xml
- notification-publisher/pom.xml
- pom.xml
- repository-meta-analyzer/pom.xml
- vulnerability-analyzer/pom.xml
We need to use the `quarkus-jacoco` extension, as well as the vanilla `jacoco-maven-plugin` in order for all test classes to be accounted for, not just those annotated with `@QuarkusTest`: https://quarkus.io/guides/tests-with-coverage#coverage-for-tests-not-using-quarkustest
Not sure if SonarCloud can pick up the non-XML formatted report though.
> Add JaCoCo

- notification-publisher/pom.xml
- repository-meta-analyzer/pom.xml
Also remove duplicate dependency of `kafka-streams-test-utils` in repo meta analyzer POM
> Fix erroneous removal of jacoco plugins

- .github/workflows/codeql.yml
Builds are failing due to https://github.com/actions/setup-java/issues/422
> Revert "Update actions/setup-java action to v3.7.0 (#143)"

- pom.xml
Downgrade dependency io.pebbletemplates:pebble to v3.1.6
> Downgrade dependency io.pebbletemplates:pebble to v3.1.6

- commons/src/main/java/org/acme/common/ApacheCommonsLoggingReflectionConfiguration.java
- commons/src/main/java/org/acme/model/AnalyzersConfig.java
- commons/src/main/java/org/acme/model/Component.java
- commons/src/main/java/org/acme/model/Vulnerability.java
- commons/src/main/java/org/acme/model/VulnerabilityResult.java
- vulnerability-analyzer/src/main/java/org/acme/client/ossindex/ComponentReport.java
- vulnerability-analyzer/src/main/java/org/acme/client/ossindex/ComponentReportRequest.java
- vulnerability-analyzer/src/main/java/org/acme/client/ossindex/ComponentReportVulnerability.java
- vulnerability-analyzer/src/main/java/org/acme/client/snyk/Issue.java
- vulnerability-analyzer/src/main/java/org/acme/client/snyk/Package.java
- vulnerability-analyzer/src/main/java/org/acme/client/snyk/Page.java
- vulnerability-analyzer/src/main/java/org/acme/client/snyk/PageData.java
- vulnerability-analyzer/src/main/java/org/acme/client/snyk/PageMeta.java
- vulnerability-analyzer/src/main/java/org/acme/client/snyk/Problem.java
- vulnerability-analyzer/src/main/java/org/acme/client/snyk/Reference.java
- vulnerability-analyzer/src/main/java/org/acme/client/snyk/Severity.java
- vulnerability-analyzer/src/main/java/org/acme/client/snyk/Slots.java
- vulnerability-analyzer/src/main/java/org/acme/processor/retry/RetryableRecord.java
Classes that are (de-)serialized with Jackson have to be explicitly registered for reflection, see https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection
Also fix `ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl`, see https://github.com/quarkusio/quarkus/issues/10128
> Fix "No serializer found for class" exceptions when running as native image

- .github/workflows/publishNativeBinary.yml
> Fix build of container image for native executable

- vulnerability-analyzer/src/main/java/org/acme/processor/retry/RetryableRecord.java
> Register RetryableRecord.JsonRecordHeader for reflection

- vulnerability-analyzer/pom.xml
Add various health and readiness endpoints.
The endpoints will be automatically picked up by the kubernetes and helm extensions.
http://localhost:8092/q/health
```json
{
"status": "UP",
"checks": [
{
"name": "Kafka Streams state health check",
"status": "UP",
"data": {
"state": "REBALANCING"
}
},
{
"name": "Database connections health check",
"status": "UP",
"data": {
"<default>": "UP"
}
},
{
"name": "Kafka Streams topics health check",
"status": "UP",
"data": {
"available_topics": "dtrack.vuln-analysis.component,dtrack.vuln-analysis.component.cpe,dtrack.vuln-analysis.component.purl,dtrack.vuln-analysis.component.swid,dtrack.vuln-analysis.vulnerability,dtrack.vuln-analysis.result,dtrack.vuln-analysis.info"
}
}
]
}
```
http://localhost:8092/q/health/live
```json
{
"status": "UP",
"checks": …
```
> Add health-, ready-, and liveness checks for vuln analyzer

- vulnerability-analyzer/src/main/java/org/acme/client/snyk/SnykClientConfiguration.java
Example metrics:
```
httpcomponents_httpclient_request_seconds_max{client="snykHttpClient",method="GET",status="200",uri="UNKNOWN",} 0.688291934
httpcomponents_httpclient_request_seconds_count{client="snykHttpClient",method="GET",status="200",uri="UNKNOWN",} 71.0
httpcomponents_httpclient_request_seconds_sum{client="snykHttpClient",method="GET",status="200",uri="UNKNOWN",} 22.204852098
```
Note that the `uri` is always "UNKNOWN". We could add it, but there really is no point given we only ever call one endpoint of the Snyk API. And the URL would include the org ID and PURL, which would result in too many metric entries.
> Export request duration metrics for Snyk HTTP client

- vulnerability-analyzer/src/main/java/org/acme/processor/ossindex/OssIndexProcessor.java
- vulnerability-analyzer/src/main/java/org/acme/processor/ossindex/OssIndexProcessorConfiguration.java
- vulnerability-analyzer/src/main/java/org/acme/processor/retry/RetryingProcessor.java
- vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessor.java
- vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessorConfiguration.java
Also enrich metrics with `thread_id` and `processor` tags, and add a new metric that will allow us to track the average size of OSS Index batches.
> Unify metric and tag names

- docker-compose.yml
- load-tests/README.md
- monitoring/grafana/dashboards/vuln-analyzer_dashboard.json
- monitoring/prometheus.yml
- scripts/profile-loadtest.sh
Also cleanup `docker-compose.yml`. Instead of having separate services for testing with Minikube, just expose an additional Kafka port at `0.0.0.0:9093` that advertises itself for `host.minikube.internal`.
Closes #206
> Add Grafana dashboard for vulnerability analyzer

- load-tests/fixtures/generate.sh
- load-tests/fixtures/images.txt
- load-tests/vuln-analyzer.js
Some etcd image versions used manifests that are incompatible with the container library that trivy uses. The `images.txt` list wasn't correctly iterated over by `generate.sh`. The `vuln-analyzer` test script has been updated to use the generated fixtures.
> Fix load test fixture generation

- monitoring/grafana/dashboards/vuln-analyzer_dashboard.json
- vulnerability-analyzer/src/main/java/org/acme/processor/internal/InternalScannerProcessor.java
- vulnerability-analyzer/src/main/java/org/acme/processor/internal/InternalScannerProcessorSupplier.java
- vulnerability-analyzer/src/main/java/org/acme/processor/ossindex/OssIndexProcessor.java
- vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessor.java
When running multiple instances of the `vuln-analyzer` service, it's now possible to view the metrics for only specific, multiple, or all of them on the Grafana dashboard.
> Support multiple instances in vuln analyzer Grafana dashboard

- repository-meta-analyzer/pom.xml
When running the repository meta analyzer as native images, it would fail to analyze Maven components with the following stacktrace:
```
java.util.MissingResourceException: Could not load any resource bundle by com.sun.org.apache.xml.internal.res.XMLErrorResources
at java.xml@17.0.5/jdk.xml.internal.SecuritySupport.lambda$getResourceBundle$5(SecuritySupport.java:280)
at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:168)
at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:318)
at java.xml@17.0.5/jdk.xml.internal.SecuritySupport.getResourceBundle(SecuritySupport.java:273)
at java.xml@17.0.5/jdk.xml.internal.SecuritySupport.getResourceBundle(SecuritySupport.java:262)
at …
```
> Fix Maven repo meta analysis failing with native image

- commons/pom.xml
- mirror-service/pom.xml
- notification-publisher/pom.xml
- pom.xml
- repository-meta-analyzer/pom.xml
- vulnerability-analyzer/pom.xml
* Define versions of dependencies that are not provided by Quarkus in the parent `pom.xml`. Avoids Renovate raising multiple PRs for the same dependency.
* Remove dependency declarations that are no longer used, or brought in transitively already.
* Replace dependencies on `jersey-common` with the Quarkus-native `quarkus-resteasy`.
> Cleanup dependency management

- docker-compose.yml
Should aid in keeping the resource footprint low when running the demo.
Exception: mirror service. We don't build native image containers for it yet.
> Use native images for demo Compose setup

- DEMO.md
- docker-compose.yml
Also limit max heap size of the container to 4GB, instead of allowing it to claim up to 90% of available RAM.
> Use pre-built API server container image for demo

- commons/src/main/java/org/hyades/common/CaffeineReflectionConfiguration.java
Something changed after upgrading Quarkus to 2.16.0.Final, causing Caffeine to use a different cache implementation behind the scenes.
```
ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSSW
2023-01-25 21:17:26     at java.base@17.0.6/java.lang.Class.forName(DynamicHub.java:1132)
2023-01-25 21:17:26     at java.base@17.0.6/java.lang.Class.forName(DynamicHub.java:1105)
2023-01-25 21:17:26     at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:84)
2023-01-25 21:17:26     at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:40)
2023-01-25 21:17:26     at …
```
> Fix ClassNotFoundException in Caffeine for native image

- .github/workflows/publishJar.yml
I missed this part when I raised #236. We currently only build these images for `amd64`.
> Build multi-platform images for jar-based distribution

- .github/dependabot.yml
All dependency versions are managed in the parent POM, there's no need to monitor all module POMs, too.
> Limit dependabot Maven ecosystem to root directory

- DEMO.md
- docker-compose.yml
hyades-apiserver does not publish `bundled` container images anymore. As such, the frontend container needs to be deployed separately for the `demo` compose profile.
I also increased the default number of Kafka Streams stream threads for the hyades services to `3`. As they're running as native executables now, it's fine to have more threads, even for cases where users have a less powerful workstation.
> Compose: Add frontend container; Increase default stream threads to 3

- repository-meta-analyzer/src/main/java/org/hyades/repositories/NugetMetaAnalyzer.java
- repository-meta-analyzer/src/test/java/org/hyades/repositories/NugetMetaAnalyzerTest.java
MetaModel was instantiated on class-level (deviating from how it was originally done in the API server). The `component` field of that `MetaModel` instance was never populated, causing problems on the API server side when consuming result events.
> Fix `NugetMetaAnalyzer` reporting `MetaModel.component` as `null`

- mirror-service/pom.xml
- mirror-service/src/main/resources/application.properties
The service does not need nor use database access, yet it still tries to connect to one and creates a connection pool. This is happening because Quarkus auto-detects entity and repository classes from the `commons` module, making the assumption that we want to use Hibernate.
> Disable database features for mirror service

- vulnerability-analyzer/src/main/java/org/hyades/VulnerabilityAnalyzerTopology.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/misc/TombstoneEmittingProcessor.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/misc/TombstoneEmittingProcessorSupplier.java
- vulnerability-analyzer/src/main/java/org/hyades/util/FixedKeyRecordFactory.java
- vulnerability-analyzer/src/test/java/org/hyades/processor/misc/TombstoneEmittingProcessorTest.java
- vulnerability-analyzer/src/test/java/org/hyades/util/FixedKeyRecordFactoryTest.java
By using `FixedKeyProcessor`, we can hint to Kafka Streams that the record key does not change while `TombstoneEmittingProcessor` is processing it.
In the current topology, this avoids **2** repartition operations, and reduces the number of sub-topologies from 6 to 4.
Before:
After:
> Avoid repartition caused by tombstone emitters

- .github/workflows/_build-native-meta.yml
- .github/workflows/ci.yml
- pom.xml
- proto/pom.xml
- proto/src/main/java/org/hyades/proto/JacksonProtobufDeserializer.java
- proto/src/main/java/org/hyades/proto/JacksonProtobufSerializer.java
- proto/src/main/java/org/hyades/proto/KafkaProtobufDeserializer.java
- proto/src/main/java/org/hyades/proto/KafkaProtobufSerde.java
- proto/src/main/java/org/hyades/proto/KafkaProtobufSerializer.java
- proto/src/main/proto/vuln-analysis-internal_v1.proto
- proto/src/main/proto/vuln-analysis_v1.proto
- proto/src/main/proto/vuln_v1.proto
- proto/src/test/java/org/hyades/proto/JacksonProtobufDeserializerTest.java
- proto/src/test/java/org/hyades/proto/JacksonProtobufSerializerTest.java
- proto/src/test/java/org/hyades/proto/KafkaProtobufSerdeTest.java
- vulnerability-analyzer/pom.xml
- vulnerability-analyzer/src/main/java/org/hyades/client/snyk/SnykClientConfiguration.java
- vulnerability-analyzer/src/main/java/org/hyades/serde/ObjectMapperCustomizer.java
- vulnerability-analyzer/src/test/java/org/hyades/processor/snyk/SnykProcessorTest.java
This PR adds an initial draft of [Protobuf](https://protobuf.dev/) schemas for use with the vulnerability analyzer, along with some serialization logic.
Custom serialization logic was needed, as the [official Protobuf serializers](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-protobuf.html) require use of a schema registry, which we decided to not use for now.
Both serialization logic and generated Java classes reside in the new `proto` module, which is intended to be used by modules within the Hyades project. Applications living outside this repo are intended to pick the `.proto` files they're interested in (e.g. `vuln-analysis_v1.proto`), and generate the corresponding code by themselves.
In later PRs, existing code in `vulnerability-analyzer` and …
> Add protobuf serializers and schemas for vulnerability analysis domain

- vulnerability-analyzer/src/main/resources/application.properties
- vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerIT.java
- vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerTestProfile.java
- vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerTopologyTest.java
- vulnerability-analyzer/src/test/java/org/hyades/client/snyk/SnykClientTest.java
- vulnerability-analyzer/src/test/java/org/hyades/persistence/VulnerableSoftwareRepositoryTest.java
- vulnerability-analyzer/src/test/java/org/hyades/processor/internal/InternalScannerProcessorTest.java
- vulnerability-analyzer/src/test/java/org/hyades/processor/ossindex/OssIndexProcessorTest.java
- vulnerability-analyzer/src/test/java/org/hyades/processor/snyk/SnykProcessorTest.java
This change will enable compression on topics in vulnerability analyser service. 
It addresses issue  https://github.com/DependencyTrack/hyades/issues/353
> enable compression

- .github/workflows/_build-native-meta.yml
Apparently 60min was a little bit too optimistic.
> Increase timeout for arm64 native builds to 75 minutes

- metrics-service/pom.xml
As long as a JDBC driver is on the classpath, Quarkus will launch a testcontainer for the respective RDBMs in test- and dev-mode. By excluding the JDBC driver, this behavior can be stopped.
This is also how it's currently done for the mirror service.
> Prevent Quarkus datasource dev services from starting for metrics service

- docker-compose.yml
* Limit max heap size of API server to `2GB`
* Limit max memory size of Redpanda to `512MB`
* Use `-native` image variants of metrics- and mirror-service
> Reduce memory footprint of demo Compose setup

- metrics-service/src/main/docker/Dockerfile.jvm
- mirror-service/src/main/docker/Dockerfile.jvm
- notification-publisher/src/main/docker/Dockerfile.jvm
- repository-meta-analyzer/src/main/docker/Dockerfile.jvm
- vulnerability-analyzer/src/main/docker/Dockerfile.jvm
It turned out that `librocksdbjndi` (brought in by RocksDB) couldn't load `libstdc++` when running the container images on arm64. It works fine on amd64 though. 
Not sure why exactly this is happening. Potentially because the [base image](https://hub.docker.com/r/bellsoft/liberica-openjdk-alpine) is a modified version of Alpine that ships with `glibc` instead of `musl`. Switching to the [`musl`-based base image](https://hub.docker.com/r/bellsoft/liberica-openjre-alpine-musl) resolves the issue, but then requires additional packages to be installed to work on amd64.
This PR has been tested on `linux/amd64` and `darwin/arm64` platforms.
> Fix JVM-based container images for arm64

- vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessor.java
We currently log a warning when the same PURL appears in multiple issues of the Snyk response.
> Avoid erroneous WARN logs during Snyk analysis

- vulnerability-analyzer/src/main/java/org/hyades/client/ossindex/ModelConverter.java
- vulnerability-analyzer/src/test/java/org/hyades/client/ossindex/ModelConverterTest.java
We previously had concerns that including the description would blow the 1MB limit of Kafka events. But now that we use Protobuf AND Snappy compression, even events with ~30 vulnerabilities end up being only ~80kiB. We'll not have any issues whatsoever with event size.
> Map description of OSS Index vulnerabilities

- repository-meta-analyzer/pom.xml
Seems like Quarkus' custom classloader in combination with multiple JAXP implementations on the classpath is the culprit. Excluding the xerces dependency inherited from the `commons` module resolves the issue.
For reference, this is the error as identified in #422:
```
2023-03-21 15:21:48,070 INFO  [repo-meta-analyzer] (docker-java-stream-1096884721) STDOUT: 2023-03-21 14:21:48,067 ERROR [org.hya.pro.MetaAnalyzerProcessor] (hyades-repository-meta-analyzer-4574539f-8ab0-4c6c-b2cd-30a9e77b9653-StreamThread-2) Failed to analyze pkg:maven/com.google.errorprone/error_prone_annotations@2.13.1?type=jar using MavenMetaAnalyzer with repository central: java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: …
```
> Fix `XPathFactoryConfigurationException` in `MavenMetaAnalyzer` when running JVM-based container image

- mirror-service/src/main/java/org/hyades/MirrorServiceTopology.java
- mirror-service/src/main/java/org/hyades/dto/OsvDto.java
Mirror service was failing with NPE when BOM did not had vulnerabilities
In native mode, since inner classes were. not registered for reflection, it could not deserialise
> Fix NPE on mirror service

- CONFIGURATION.md
- docker-compose.yml
API_TOPIC_PREFIX is an optional environment variable and now also added to the redpanda init container so we can create topics with required prefix
> added api_topic_prefix in the environment variables of init container

- .github/workflows/e2e.yml
- README.md
- e2e/pom.xml
- e2e/src/main/java/org/hyades/apiserver/ApiServerClient.java
- e2e/src/main/java/org/hyades/apiserver/ApiServerClientHeaderFactory.java
- e2e/src/main/java/org/hyades/apiserver/model/ApiKey.java
- e2e/src/main/java/org/hyades/apiserver/model/BomProcessingResponse.java
- e2e/src/main/java/org/hyades/apiserver/model/BomUploadRequest.java
- e2e/src/main/java/org/hyades/apiserver/model/BomUploadResponse.java
- e2e/src/main/java/org/hyades/apiserver/model/ConfigProperty.java
- e2e/src/main/java/org/hyades/apiserver/model/CreateNotificationRuleRequest.java
- e2e/src/main/java/org/hyades/apiserver/model/CreateTeamRequest.java
- e2e/src/main/java/org/hyades/apiserver/model/CreateVulnerabilityRequest.java
- e2e/src/main/java/org/hyades/apiserver/model/Finding.java
- e2e/src/main/java/org/hyades/apiserver/model/NotificationPublisher.java
- e2e/src/main/java/org/hyades/apiserver/model/NotificationRule.java
- e2e/src/main/java/org/hyades/apiserver/model/Project.java
- e2e/src/main/java/org/hyades/apiserver/model/Team.java
- e2e/src/main/java/org/hyades/apiserver/model/UpdateNotificationRuleRequest.java
- e2e/src/test/java/org/hyades/e2e/AbstractE2ET.java
- e2e/src/test/java/org/hyades/e2e/AbstractE2eTest.java
- e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
- e2e/src/test/java/org/hyades/e2e/BomUploadProcessingTest.java
- e2e/src/test/resources/dtrack-apiserver-4.5.0.bom.json
- pom.xml
- scripts/create-topics.sh
This PRs lays the groundwork for end-to-end tests, incorporating all services and infrastructure components of the system.
Some cornerstones of the current implementation:
* [testcontainers](https://www.testcontainers.org/) is used to setup and tear down containers for every test case
* [WireMock](https://wiremock.org/) is used to verify Webhook alerts
* [GreenMail](https://greenmail-mail-test.github.io/greenmail/) is used to verify email alerts
* No Quarkus / CDI context is spun up to keep the tests simple and as lightweight as possible
* End-to-end tests live in the `e2e` module, and *must* be suffixed with `E2ET` to distinguish them from integration tests (`*IT`)
* End-to-end tests are skipped per default, enabling them requires usage of the `e2e-all` Maven profile
* End-to-end tests …
> Initial work for end-to-end tests

- .github/workflows/ci.yml
Integration tests cover cases that unit tests do not. 
At the moment, we only run ITs against native binaries, because that's the only way we can test those.
Quarkus will execute ITs against the built JARs.
> Run integration tests in CI workflow

- monitoring/grafana/dashboards/mirror-service_dashboard.json
- monitoring/grafana/dashboards/notification-publisher_dashboard.json
- monitoring/grafana/dashboards/repo-meta-analyzer_dashboard.json
- monitoring/grafana/dashboards/vuln-analyzer_dashboard.json
- notification-publisher/src/main/resources/application.properties
This ensures that the dashboards do not include data from ALL hyades services, but only from the services the respective dashboard is supposed to display.
> Add filters to `instance` variable of Grafana dashboards

- mirror-service-x/pom.xml
- mirror-service-x/src/main/java/io/github/jeremylong/ghsa/GitHubSecurityAdvisoryClientBuilder.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/KafkaProducerProducer.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/AbstractDatasourceMirror.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/DatasourceMirror.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubApiClientFactory.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubConfig.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubMirror.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubMirrorConfiguration.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdApiClientFactory.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdConfig.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdMirror.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdMirrorConfiguration.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/state/MirrorStateStore.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/state/StateStoreUpdater.java
- mirror-service-x/src/main/java/org/hyades/vulnmirror/state/StateStores.java
- mirror-service-x/src/main/resources/application.properties
- mirror-service-x/src/test/java/org/hyades/util/WireMockTestResource.java
- mirror-service-x/src/test/java/org/hyades/vulnmirror/KafkaStreamsTopologyIT.java
- mirror-service-x/src/test/java/org/hyades/vulnmirror/TestConstants.java
- mirror-service-x/src/test/java/org/hyades/vulnmirror/datasource/github/GitHubMirrorTest.java
- mirror-service-x/src/test/java/org/hyades/vulnmirror/datasource/nvd/NvdMirrorTest.java
- mirror-service-x/src/test/java/org/hyades/vulnmirror/state/MirrorStateStoreTest.java
- mirror-service-x/src/test/java/org/hyades/vulnmirror/state/VulnerabilityDigestStoreTest.java
- mirror-service-x/src/test/resources/datasource/github/advisories-page-01.json
- mirror-service-x/src/test/resources/datasource/github/advisories-page-02.json
- mirror-service-x/src/test/resources/datasource/github/advisory.json
- mirror-service-x/src/test/resources/datasource/nvd/cve.json
- mirror-service-x/src/test/resources/datasource/nvd/cves-page-01.json
- mirror-service-x/src/test/resources/datasource/nvd/cves-page-02.json
This PR adds unit- and integration-tests for the existing mirroring logic.
A few additional minor changes are included as well:
* Sending of notifications when a mirroring operation succeeded or failed, [analog](https://github.com/DependencyTrack/dependency-track/blob/4.7.1/src/main/java/org/dependencytrack/tasks/NistMirrorTask.java#L256-L275) to how it's done in vanilla DT
* Timer metrics for mirroring operations
* Health endpoint via [SmallRye Health](https://quarkus.io/guides/smallrye-health)
* Proper closing of the Kafka producer during application shutdown
> Add tests for reworked mirror service

- e2e/src/main/java/org/hyades/apiserver/model/Finding.java
- e2e/src/test/java/org/hyades/e2e/BomUploadOssIndexAnalysisE2ET.java
- e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
- e2e/src/test/java/org/hyades/e2e/BomUploadSnykAnalysisE2ET.java
This will make it easier to quickly verify if the analyzers still work as expected.
> **Note**  
> In order to run the Snyk test, the `SNYK_ORG_ID` and `SNYK_TOKEN` environment variables need to be set.
> Add end-to-end tests for OSS Index and Snyk analysis

- notification-publisher/src/main/resources/application.properties
- repository-meta-analyzer/src/main/resources/application.properties
To make compression consistent across services.
Event though the notification publisher does not emit any events by itself, enabling snappy will cause the libsnappy.so library to be embedded into the native image of the service. That library is required to decompress received events.
Required for compatibility with https://github.com/DependencyTrack/hyades-apiserver/pull/79
> Enable Snappy compression for notification-publisher and repository-meta-analyzer

- .github/workflows/publishJar.yml
- e2e/src/test/java/org/hyades/e2e/BomUploadOssIndexAnalysisE2ET.java
- e2e/src/test/java/org/hyades/e2e/BomUploadSnykAnalysisE2ET.java
Should hopefully suffice to be able to run E2E tests with OSS Index in CI.
Referenced secrets have been added on the repository level in GitHub.
> Provide OSS Index credentials to E2E tests; Increase timeout

- mirror-service/pom.xml
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdConfig.java
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdMirror.java
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdMirrorConfiguration.java
- mirror-service/src/test/java/org/hyades/vulnmirror/datasource/nvd/NvdMirrorTest.java
**Description**
This PR adds retry logic to nvd mirror task that will help to deal with random gibberish seen while running NVD mirroring task as also raised here: https://github.com/jeremylong/vuln-tools/issues/42#issuecomment-1461860163
Closes issue: https://github.com/DependencyTrack/hyades/issues/489
Added corresponding unit tests as well
> Retry added to NvdMirror task

- mirror-service/src/main/resources/application.properties
- notification-publisher/src/main/resources/application.properties
- repository-meta-analyzer/src/main/resources/application.properties
- vulnerability-analyzer/src/main/resources/application.properties
disabling system properties mapping in helm chart creation to avoid confusion.
For example: we have a property called api.topic.prefix that is part of application properties and used to set values of other properties in the same file as well. 
Due to this setup, quarkus helm extension is considering it as a system property and creating a corresponding entry in the deployment chart created like this:
api:
topic:
prefix: ""
This property is not being used and creates confusion with us also passing explicit environment variable called: API_TOPIC_PREFIX.
This change disables mapping of system properties so that these values are no longer added to automatically created deployment chart
> Disable mapping of system properties in helm chart creation

- docker-compose.yml
Bumps Redpanda to v23.1.7, and Redpanda Console to v2.2.3.
Also adds missing topic mappings for Redpanda Console.
> Bump Redpanda

- repository-meta-analyzer/src/main/java/org/hyades/repositories/GoModulesMetaAnalyzer.java
- repository-meta-analyzer/src/test/java/org/hyades/RepositoryMetaAnalyzerIT.java
Timestamps in responses of the Go module proxy are specified for the UTC timezone, but we currently parse it at the system's default time zone instead.
> Ensure timestamps for Go modules are parsed as UTC

- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
- pom.xml
Upgrade to the latest version of the `open-vulnerability-clients` library; supersedes #509.
- [Release notes for 4.0.0](https://github.com/jeremylong/Open-Vulnerability-Project/releases/tag/v4.0.0)
- Add data feed client for First.org [Exploit Prediction Scoring System (EPSS)](https://www.first.org/epss/)
- Add data feed client for CISA's [Known Exploited Vulnerabilities Catalog](https://www.cisa.gov/known-exploited-vulnerabilities-catalog)
- Breaking change: updated all usage of Float data types for scores to BigDecimal to preserve accuracy
- [Release notes for 4.0.1](https://github.com/jeremylong/Open-Vulnerability-Project/releases/tag/v4.0.1)
- minor update to the dependencies of the vulnz cli
- removed the use of deprecated function
> build(deps): bump open-vulnerability-clients from 3.0.0 to 4.0.1

- commons/pom.xml
- e2e/pom.xml
- mirror-service/pom.xml
- notification-publisher/pom.xml
- pom.xml
- repository-meta-analyzer/pom.xml
- vulnerability-analyzer/pom.xml
Adds the log4j-over-slf4j logging bridge which is needed to see DataNucleus log output.
https://github.com/DependencyTrack/hyades/issues/374
> DataNucleus: Add logging bridge

- docker-compose.yml
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubReflectionConfiguration.java
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdReflectionConfiguration.java
- mirror-service/src/main/resources/application.properties
- notification-publisher/src/main/resources/application.properties
- repository-meta-analyzer/src/main/resources/application.properties
- vulnerability-analyzer/src/main/resources/application.properties
The mirror service was failing in the demo setup, because:
* Only `QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS` was set, but this env variable is not picked up by the internal Kafka producer that is not managed by Kafka Streams
* The reflection registration for NVD and GitHub classes was missing, causing deserialization issues when running the native image
I have also gone ahead and replaced all usages of `QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS` with `KAFKA_BOOTSTRAP_SERVERS`. It will be picked up by both non-Kafka Streams, and Kafka Streams clients.
> Fix mirror service demo setup

- CONFIGURATION.md
- TOPICS.md
- proto/src/main/proto/org/hyades/vulnanalysis/internal/v1beta1/vuln_analysis_internal.proto
- vulnerability-analyzer/src/main/java/org/hyades/VulnerabilityAnalyzerTopology.java
- vulnerability-analyzer/src/main/java/org/hyades/config/RocksDbConfigSetter.java
- vulnerability-analyzer/src/main/java/org/hyades/config/StateStoreConfig.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/misc/ScannerResultAggregator.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/misc/ScannerResultAggregatorSupplier.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/misc/TombstoneEmittingProcessorSupplier.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/ossindex/OssIndexProcessorConfiguration.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/snyk/SnykProcessorConfiguration.java
- vulnerability-analyzer/src/main/java/org/hyades/util/StateStoreUtil.java
- vulnerability-analyzer/src/main/resources/application.properties
- vulnerability-analyzer/src/test/java/org/hyades/processor/misc/ScannerResultAggregatorTest.java
- vulnerability-analyzer/src/test/java/org/hyades/processor/misc/TombstoneEmittingProcessorTest.java
This PR introduces some improvements to how Kafka Streams state stores are used in the vulnerability-analyzer.
The `completed-scans-table` store is where we aggregate results from all applicable scanners, per `ScanKey`. The intention is to only forward a result events to `dtrack.vuln-analysis.result` once all scanners completed their work. The store was prone to accumulating lots of data, for the following reasons:
1. Scanner results can be quite big (depending on how many vulnerabilities were identified). The data is compressed in Kafka topics, but it's uncompressed in the local state store.
2. `KTable`s do not support manual deletions or TTL policies, so entries never expire and stay around forever
3. The default `segment.bytes` for changelog topics is 256 MiB. Kafka can only delete …
> Optimize state store usage

- vulnerability-analyzer/src/main/java/org/hyades/config/RocksDbConfigSetter.java
Kafka streams instantiates the configured class via reflection. Because the class is not directly referenced right now, the vuln analyzer currently does not start when running via native image.
> Register `RocksDbConfigSetter` for reflection

- mirror-service/src/main/docker/Dockerfile.jvm
- notification-publisher/src/main/docker/Dockerfile.jvm
- repository-meta-analyzer/src/main/docker/Dockerfile.jvm
- vulnerability-analyzer/src/main/docker/Dockerfile.jvm
https://github.com/DependencyTrack/hyades/issues/561 
Fix signals (e.g. SIGTERM) not being handled by the JVM process inside the container image, preventing graceful shutdown.
> fix SIGTERM container handling

- helm-charts/hyades/templates/vuln-analyzer/service.yaml
Port definition is required for binding ingress or routes to the service (although this should be rare).
> Helm: Add port definition to vuln analyzer service

- commons/pom.xml
- commons/src/test/resources/application.properties
- notification-publisher/pom.xml
- notification-publisher/src/main/resources/application.properties
- repository-meta-analyzer/pom.xml
- repository-meta-analyzer/src/main/resources/application.properties
- repository-meta-analyzer/src/test/java/org/hyades/RepositoryMetaAnalyzerIT.java
- vulnerability-analyzer/pom.xml
- vulnerability-analyzer/src/main/resources/application.properties
- vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerIT.java
As of Quarkus 2.16.3 it is possible to provide an init script to the database testcontainer (https://github.com/quarkusio/quarkus/pull/30455).
We previously had to use Flyway to initialize the container with the API server SQL schema. This is no longer necessary.
> Replace Flyway with testcontainers init script

- helm-charts/hyades/templates/_helpers.tpl
- helm-charts/hyades/templates/api-server/ingress.yaml
- helm-charts/hyades/templates/api-server/pvc.yaml
- helm-charts/hyades/templates/api-server/service.yaml
- helm-charts/hyades/templates/api-server/statefulset.yaml
- helm-charts/hyades/templates/frontend/deployment.yaml
- helm-charts/hyades/templates/frontend/ingress.yaml
- helm-charts/hyades/templates/frontend/service.yaml
- helm-charts/hyades/templates/mirror-service/deployment.yaml
- helm-charts/hyades/templates/notification-publisher/deployment.yaml
- helm-charts/hyades/templates/repo-meta-analyzer/deployment.yaml
- helm-charts/hyades/templates/vuln-analyzer/service.yaml
- helm-charts/hyades/templates/vuln-analyzer/statefulset.yaml
* Properly truncate `name` and `fullname` such that they never exceed 63 characters, even with suffixes
* Add `app.kubernetes.io/part-of` label
* Make `app.kubernetes.io/name` specific to individual services, instead of using a common label values across all services
* Use fully qualified names in `metadata.name`
> Revise labels in Helm chart

- helm-charts/hyades/templates/api-server/ingress.yaml
- helm-charts/hyades/templates/api-server/pvc.yaml
- helm-charts/hyades/templates/frontend/deployment.yaml
- helm-charts/hyades/templates/frontend/ingress.yaml
- helm-charts/hyades/templates/mirror-service/deployment.yaml
- helm-charts/hyades/templates/repo-meta-analyzer/deployment.yaml
I missed to move some resources from `*SelectorLabels` to `*Labels` for `metadata.labels` fields in #583, leading to inconsistencies in labels across resources.
> Fix inconsistent usage of labels in Helm chart

- .github/workflows/_build-native-meta.yml
- .github/workflows/buf.yml
- .github/workflows/build-native-mirror-service.yml
- .github/workflows/build-native-notification-publisher.yml
- .github/workflows/build-native-repository-meta-analyzer.yml
- .github/workflows/build-native-vulnerability-analyzer.yml
- .github/workflows/ci.yml
- .github/workflows/helm-ci.yml
- .github/workflows/publishJar.yml
- .github/workflows/semgrep.yml
Pin versions of Actions to their digest, and drop token permissions wherever possible.
Dependabot will take care of updating the actions properly, as it is capable of interpreting the `tag=vX.X.X` comment.
Token permissions are dropped globally for every GHA workflow. When specific permissions are required (e.g. to publish container images), those permissions are specified on the `jobs` level.
See also:
* https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
* https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
> Lock down GitHub Actions workflows

- .github/workflows/build-native-mirror-service.yml
- .github/workflows/build-native-notification-publisher.yml
- .github/workflows/build-native-repository-meta-analyzer.yml
- .github/workflows/build-native-vulnerability-analyzer.yml
Reusable workflows like this one cannot have more permissions than the workflow calling them (https://docs.github.com/en/actions/using-workflows/reusing-workflows#access-and-permissions). 
Because `build-native-mirror-service.yml` etc. dropped all permissions, `_build-native-meta.yml` can't request the `packages: write` permission.
Build pipelines for native images are currently failing due to this, e.g. https://github.com/DependencyTrack/hyades/actions/runs/5248293048
> Fix insufficient token permissions in `_build_native_meta.yml`

- pom.xml
Fixes GHSA-qcwq-55hx-v3vh, GHSA-fjpj-2g6w-x25r, and GHSA-pqr6-cmr2-h8hf
> Update `snappy-java` to 1.1.10.1

- .github/workflows/ci.yml
- mirror-service/src/main/java/org/hyades/vulnmirror/config/KafkaStreamsReflectionConfiguration.java
- repository-meta-analyzer/src/main/java/org/hyades/config/KafkaStreamsReflectionConfiguration.java
- vulnerability-analyzer/src/main/java/org/hyades/config/KafkaStreamsReflectionConfiguration.java
As of kafka-streams 3.5.0, users can configure a KafkaClientSupplier, with the default implementation being `DefaultKafkaClientSupplier` (https://issues.apache.org/jira/browse/KAFKA-14395).
The supplier is called via reflection, but Quarkus <= 3.1.x doesn't yet register it as such for GraalVM.
> Fix broken native images after KStreams upgrade

- CONFIGURATION.md
- mirror-service/pom.xml
- mirror-service/src/main/resources/application.properties
- notification-publisher/pom.xml
- notification-publisher/src/main/resources/application.properties
- repository-meta-analyzer/pom.xml
- repository-meta-analyzer/src/main/resources/application.properties
- vulnerability-analyzer/pom.xml
- vulnerability-analyzer/src/main/resources/application.properties
Defaults to off in order to be more human-readable.
Example log entry:
```json
{"timestamp":"2023-06-23T11:55:24.627+02:00","sequence":2333,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.deployment.dev.RuntimeUpdatesProcessor","level":"INFO","message":"Live reload total time: 1.348s ","threadName":"Aesh InputStream Reader","threadId":91,"mdc":{},"ndc":"","hostName":"ctrl","processName":"mirror-service-dev.jar","processId":33646}
```
Closes #618
> Add support for logging in JSON format

- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/AbstractDatasourceMirror.java
- mirror-service/src/main/resources/application.properties
- mirror-service/src/test/java/org/hyades/vulnmirror/KafkaStreamsTopologyIT.java
- notification-publisher/src/main/java/org/hyades/notification/config/ProtoReflectionConfiguration.java
- proto/src/main/java/org/hyades/proto/KafkaProtobufSerializer.java
- proto/src/test/java/org/hyades/proto/KafkaProtobufSerdeTest.java
The GitHub advisory client loads template files from classpath, which are not packaged into the native image by default.
> Fix native image tests for mirror-service

- docker-compose.yml
We currently cannot guarantee that the native builds work as intended (#641). We can switch this back once we are more confident with native builds.
> Use JVM-based images for `docker-compose.yml`

- e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
As of https://github.com/DependencyTrack/hyades-apiserver/pull/218, the project's PURL is ingested from the uploaded BOM.
> Fix `BomUploadProcessingE2ET`

- notification-publisher/src/main/java/org/hyades/notification/config/ProtoReflectionConfiguration.java
Fixes the notification-publisher's native image integration test
> Add missing proto classes to notification-publisher's reflection config

- .github/workflows/_build-native-meta.yml
- .github/workflows/ci.yml
- mirror-service/src/main/resources/application.properties
The `graalvm/setup-graalvm` action defaults to using the new Oracle GraalVM distribution, which causes failures with Protobuf serialization.
Trying to install Mandrel using the action doesn't work; It still installs Oracle GraalVM on top of it, see for example https://github.com/DependencyTrack/hyades/actions/runs/5724111667/job/15509962852
```
Run graalvm/setup-graalvm@v1
with:
distribution: mandrel
version: mandrel-latest
java-version: 17
components: native-image
github-token: ***
set-java-home: true
check-for-updates: true
native-image-musl: false
native-image-job-reports: false
native-image-pr-reports: false
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64
JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64
/usr/bin/tar xz …
```
> Fix native image integration tests

- notification-publisher/src/main/java/org/hyades/notification/config/ParallelConsumerConfiguration.java
- pom.xml
See https://github.com/confluentinc/parallel-consumer/releases/tag/0.5.2.6 for release notes
> Bump parallel consumer to 0.5.2.6

- .github/release.yml
- .github/workflows/_build-native-meta.yml
- .github/workflows/publishJar.yml
- .github/workflows/release.yml
- commons-kstreams/pom.xml
- commons-persistence/pom.xml
- commons/pom.xml
- e2e/pom.xml
- notification-publisher/pom.xml
- pom.xml
- proto/pom.xml
- repository-meta-analyzer/pom.xml
Releases can now be triggered via GitHub UI, under *Actions* -> *Release* -> *Run Workflow*.
Beside creating a Git tag for the release, this workflow:
* Builds and pushes JVM-based container images (no native images for now)
* Creates a GitHub release with auto generated release notes
* Generates CycloneDX BOMs for all applications and attaches them to the GitHub release
An example execution can be found here: https://github.com/nscuro/hyades/actions/runs/5718792194/job/15495340977
An example release can be found here: https://github.com/nscuro/hyades/releases/tag/v1.11.0
Closes #708
> Add release workflow

- .github/workflows/publishJar.yml
- .github/workflows/release.yml
Image names are not allowed to contain uppercase characters. #709 introduced a change where the `group` part of the image name would come from the GitHub repository's owner (e.g. `DependencyTrack`), which can contain uppercase characters.
Fixed by using Bash expansion on the `GITHUB_REPOSITORY_OWNER` environment variable, to convert it to lowercase.
> Fix container image group not being lower-cased

- commons-persistence/src/main/java/org/hyades/persistence/model/Repository.java
- repository-meta-analyzer/src/main/java/org/hyades/processor/MetaAnalyzerProcessor.java
Default auth required and is internal to False. This is needed to avoid downstream errors.
> Default auth required and is internal to False

- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubMirrorConfiguration.java
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdMirrorConfiguration.java
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/osv/OsvMirrorConfiguration.java
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/util/LoggingRejectedExecutionHandler.java
- mirror-service/src/main/java/org/hyades/vulnmirror/datasource/util/LoggingUncaughtExceptionHandler.java
- mirror-service/src/test/java/org/hyades/vulnmirror/datasource/util/LoggingRejectedExecutionHandlerTest.java
- mirror-service/src/test/java/org/hyades/vulnmirror/datasource/util/LoggingUncaughtExceptionHandlerTest.java
Task execution rejections and otherwise uncaught exceptions are now logged, using the logger of the respective `DatasourceMirror` class.
> Fix mirror task rejection causing KStreams to fail

- e2e/src/test/java/org/hyades/e2e/AbstractE2ET.java
As of https://github.com/DependencyTrack/hyades/pull/709, unreleased `main` builds are no longer tagged as `latest`, but `snapshot` instead.
> Run e2e tests against `snapshot` tags

- .github/workflows/release.yml
GitHub Actions can't be added to accounts that are allowed by bypass branch protection rules.
> Use `dependencytrack-bot` account to push commits to `main` during release

- e2e/src/main/java/org/hyades/apiserver/model/CreateVulnerabilityRequest.java
- e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
- notification-publisher/src/test/java/org/hyades/notification/NotificationRouterTest.java
- notification-publisher/src/test/java/org/hyades/notification/publisher/WebhookPublisherTest.java
- proto/src/main/proto/org/hyades/notification/v1/notification.proto
Companion change to https://github.com/DependencyTrack/hyades-apiserver/pull/290
Note: Because the original field numbers and types remain untouched, this is not a breaking change schema-wise. The name of the fields has changed, but this is only relevant to the JSON output, which is exactly what we want to fix here.
> Fix breaking change in `NEW_VULNERABILITY` notification JSON format

- e2e/src/test/java/org/hyades/e2e/AbstractE2ET.java
- e2e/src/test/java/org/hyades/e2e/BomProcessedNotificationDelayedE2ET.java
Adds an e2e test for the delayed `BOM_PROCESSED` notification feature, introduced in https://github.com/DependencyTrack/hyades-apiserver/pull/299
> Add e2e test for delayed `BOM_PROCESSED` notification

- vulnerability-analyzer/src/main/java/org/hyades/processor/misc/ScannerResultAggregator.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/retry/RetryingBatchProcessor.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/ossindex/OssIndexProcessor.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/snyk/SnykProcessor.java
When RocksDB state stores are enabled (`STATE_STORE_TYPE=rocks_db`), there was a possibility that under low-traffic circumstances, records in a scanner's `batchStore` were not submitted for analysis.
This is because the `approximateNumEntries` method can differ vastly from the *actual* number of entries in the store.
We use `approximateNumEntries` to short-circuit the punctuator responsible for submitting incomplete batches on a schedule
I temporarily modified the respective code to log both the result of `approximateNumEntries`, as well as the *actual* number of entries:
```java
final long batchStoreSize = batchStore.approximateNumEntries();
if (batchStoreSize == 0) {
final long actual = Iterators.size(batchStore.all());
logger.info("Current batch is empty (rocks={}, actual={})", …
```
> Fix batches not being submitted even though `batchStore` contains records

- e2e/src/test/java/org/hyades/e2e/BomProcessedNotificationDelayedE2ET.java
- e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
- notification-publisher/src/main/java/org/hyades/notification/publisher/PublishContext.java
- notification-publisher/src/main/java/org/hyades/notification/publisher/Publisher.java
- notification-publisher/src/test/java/org/hyades/notification/NotificationRouterIT.java
- notification-publisher/src/test/java/org/hyades/notification/publisher/ConsolePublisherTest.java
- notification-publisher/src/test/java/org/hyades/notification/publisher/PublishContextTest.java
- notification-publisher/src/test/java/org/hyades/notification/publisher/WebhookPublisherTest.java
- proto/src/main/java/org/hyades/proto/ProtobufUtil.java
- proto/src/test/java/org/hyades/proto/ProtobufUtilTest.java
Adds a custom method for formatting Protobuf `Timestamp`s.
With the default `Timestamps#toString` method, the format could change slightly, depending on how precise the provided `Timestamp` was. The number of fractional digit could either be of length 0, 3, 6, or 9. To prevent any complications in timestamp parsing, we settle for a fixed length of 3.
> Ensure consistent formatting of notification timestamps

- vulnerability-analyzer/src/main/java/org/hyades/VulnerabilityAnalyzerTopology.java
Kafka Streams works based on topologies. It relies on the fact that the *exact* same topology is present on all instances of a KS app. This means that the order of topology nodes must be identical.
For the vulnerability-analyzer, users can enable or disable individual scanners. Only enabled scanners will be added to the topology on startup.
Scanners are CDI beans, and we inject all of them via [`Instance`](https://jakarta.ee/specifications/cdi/3.0/apidocs/jakarta/enterprise/inject/instance). `Instance` can contain zero or more beans.
Scanners are added to the topology by iterating over the `Instance` bean. The problem here is that the order of the beans in `Instance` is not guaranteed. It could happen that instance A of the service added scanners in the order 123, whereas instance B added …
> Fix potential `TopologyException` when running multiple vulnerability-analyzer instances

- helm-charts/hyades/README.md
- helm-charts/hyades/templates/mirror-service/deployment.yaml
- helm-charts/hyades/values.yaml
Allows the deployment to be scaled down to zero pods, which was not possible with the hardcoded replicaCount of `1`.
> Make replicaCount configurable for mirror-service

- commons/src/main/java/org/hyades/commonutil/DateUtil.java
- commons/src/test/java/org/hyades/commonutil/DateUtilTest.java
- proto/src/main/proto/org/hyades/repometaanalysis/v1/repo_meta_analysis.proto
- repository-meta-analyzer/src/main/java/org/hyades/RepositoryMetaAnalyzerTopology.java
- repository-meta-analyzer/src/main/java/org/hyades/model/IntegrityMeta.java
- repository-meta-analyzer/src/main/java/org/hyades/processor/MetaAnalyzerProcessor.java
- repository-meta-analyzer/src/main/java/org/hyades/processor/MetaAnalyzerProcessorSupplier.java
- repository-meta-analyzer/src/main/java/org/hyades/repositories/AbstractMetaAnalyzer.java
- repository-meta-analyzer/src/main/java/org/hyades/repositories/IMetaAnalyzer.java
- repository-meta-analyzer/src/main/java/org/hyades/repositories/MavenMetaAnalyzer.java
- repository-meta-analyzer/src/main/java/org/hyades/repositories/NpmMetaAnalyzer.java
- repository-meta-analyzer/src/main/java/org/hyades/repositories/PypiMetaAnalyzer.java
- repository-meta-analyzer/src/main/java/org/hyades/util/PurlUtil.java
- repository-meta-analyzer/src/test/java/org/hyades/RepositoryMetaAnalyzerIT.java
- repository-meta-analyzer/src/test/java/org/hyades/RepositoryMetaAnalyzerTopologyTest.java
- repository-meta-analyzer/src/test/java/org/hyades/processor/MetaAnalyzerProcessorTest.java
- repository-meta-analyzer/src/test/java/org/hyades/repositories/HexMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/hyades/repositories/MavenMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/hyades/repositories/NpmMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/hyades/repositories/PypiMetaAnalyzerTest.java
Issue: https://github.com/DependencyTrack/hyades/issues/699
> Integrate Integrity metadata in repo-meta-analyzer

- .github/workflows/ci.yml
Caused by https://github.com/graalvm/setup-graalvm/issues/64
> Fix failing `setup-graalvm` action

- pom.xml
All CycloneDX related communication is done through Protocol Buffers, the Java library is not used anymore.
Closes #849
> Remove dependency on `cyclonedx-core-java`

- commons/src/main/java/org/hyades/common/cwe/CweDefinitions.java
- scripts/generate-cwe-definitions.py
Companion PR to https://github.com/DependencyTrack/hyades-apiserver/pull/369
> Bump CWE dictionary to v4.12

- commons-persistence/pom.xml
- commons-persistence/src/main/java/org/hyades/persistence/repository/VulnerableSoftwareRepository.java
- vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/internal/InternalScannerProcessor.java
- vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/internal/InternalScannerProcessorTest.java
Ported from https://github.com/DependencyTrack/dependency-track/pull/3070
> Fix false negatives in NVD CPE matching

- .github/workflows/deploy-docs.yml
This makes the docs' versioning functionality work properly. Users will be able to switch between doc versions.
> Build and publish docs upon release

- .github/workflows/_build-native-meta.yml
- .github/workflows/build-native-mirror-service.yml
- .github/workflows/build-native-notification-publisher.yml
- .github/workflows/build-native-repository-meta-analyzer.yml
- .github/workflows/build-native-vulnerability-analyzer.yml
Native images are built upon release now.
They'll be tagged as `<RELEASE_VERSION>-native`.
Additionally, they'll be tagged as `snapshot-native` or `latest-native`, depending on whether the build is happening for a `-SNAPSHOT` version or not. 
Closes #718
> Build and publish native images on release

- .github/workflows/ci.yml
As the test suites grow they sometimes take longer than 25min to run, causing unnecessary CI failures. Bumping the timeouts by 5min.
> Increase timeout of test workflows

- mirror-service/src/main/resources/application.properties
- repository-meta-analyzer/src/main/resources/application.properties
- vulnerability-analyzer/src/main/resources/application.properties
See comments in `application.properties` for an explanation why. Will likely raise an issue with Quarkus for this.
> Fix `repartition.purge.interval.ms` not being configurable via environment variables

- pom.xml
Instead of relying on Quarkus bringing it in transitively, specify the Protobuf version explicitly, and also use that for `protoc`.
This is analog to how it's done in the API server.
> Align Protobuf version with API server

- commons/src/main/java/org/hyades/config/HttpClientConfig.java
The previous defaults of 30s for connection-, and 30s for socket timeouts are too excessive for a system that needs to maintain high-ish throughput.
These values are aligned with what's configured for the Quarkus REST client in the vulnerability analyzer.
> Reduce default HTTP client timeouts

- .gitattributes
When checking out the repository, bash scripts would use the platform's native line breaks, which when done on Windows would break the scripts for Linux containers. One of them being the `create-topics.sh` script we mount into the `redpanda-init` container.
> Fix line break issues when cloning repository on Windows

- docker-compose.yml
- helm-charts/hyades/README.md
- helm-charts/hyades/templates/_helpers.tpl
- helm-charts/hyades/values.yaml
We haven't officially forked the frontend yet, and the official frontend doesn't support CEL and integrity analysis yet.
This PR adds a customized v4.9.1 image that includes both functionalities. It was built from https://github.com/sahibamittal/dependency-track-frontend-upstream/commit/33d2b0086241b98c8f4a288caa938fb39362417e.
> Use custom frontend with CEL and integrity analysis support

- e2e/pom.xml
- e2e/src/main/java/org/dependencytrack/apiserver/ApiServerClient.java
- e2e/src/main/java/org/dependencytrack/apiserver/model/Analysis.java
- e2e/src/main/java/org/dependencytrack/apiserver/model/Finding.java
- e2e/src/main/java/org/dependencytrack/apiserver/model/VulnerabilityPolicy.java
- e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/BomUploadOssIndexAnalysisE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/BomUploadProcessingE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/BomUploadSnykAnalysisE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
- pom.xml
The test includes:
* Pulling policies from S3 (MinIO)
* Reconciliation of policies with database
* Application of policies for suppression and rating downgrade
* Verification of notifications sent
Closes #960
> [!NOTE]
> Requires https://github.com/DependencyTrack/hyades-apiserver/pull/493 to succeed.
> Add e2e test for vulnerability policies

- docs/usage/policy-compliance/expressions.md
Reflecting the changes made in https://github.com/DependencyTrack/hyades-apiserver/pull/497
> Update docs with shortened CEL type namespace

- vulnerability-analyzer/src/main/java/org/dependencytrack/client/snyk/ModelConverterToCdx.java
- vulnerability-analyzer/src/test/java/org/dependencytrack/client/snyk/ModelConverterToCdxTest.java
Originally this should only happen when the main ID of a vulnerability followed a legacy format. Now, it seems like `SNYK-` vulnerabilities can also reference other `SNYK-` vulnerabilities.
> Fix confusion of IDs when `SNYK-` vulnerabilities are reported in `problems` array

- docker-compose.yml
It's no longer used as per #1031
> Remove `CEL_POLICY_ENGINE_ENABLED` from `docker-compose.yml`

- .github/workflows/_build-native-meta.yml
- .github/workflows/ci.yml
- .idea/runConfigurations/Build_Native.xml
- .idea/runConfigurations/Run_Native_Integration_Tests.xml
- commons-persistence/pom.xml
- mirror-service/pom.xml
- notification-publisher/pom.xml
- pom.xml
- repository-meta-analyzer/pom.xml
- vulnerability-analyzer/pom.xml
As per Mandrel 23.1, the native image build fails when modules depend on `com.google.cloud.sql:postgres-socket-factory`: https://github.com/DependencyTrack/hyades/actions/runs/7686438316/job/20945288653. Apparently it uses a special way to call native libraries, which is not supported.
This change only includes the dependency when explicitly *not* building in native mode.
Also added an IntelliJ run profile to build native executables using containers, removing the requirement of having Graal / Mandrel installed.
> Fix broken native build caused by Cloud SQL socket factory

- e2e/src/main/java/org/dependencytrack/apiserver/ApiServerClient.java
- e2e/src/main/java/org/dependencytrack/apiserver/model/WorkflowTokenResponse.java
- e2e/src/test/java/org/dependencytrack/e2e/BomProcessedNotificationDelayedE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/BomUploadOssIndexAnalysisE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/BomUploadProcessingE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/BomUploadSnykAnalysisE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
Incorporates manual sync trigger in vulnerability policy e2e test.
Requires https://github.com/DependencyTrack/hyades-apiserver/pull/528
Relates to #1008
> Incorporate manual sync trigger in vuln policy e2e test

- .github/workflows/_build-native-meta.yml
See announcement: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
Note: The build on macOS still produces a Linux binary, because we're running the build in a container (`quarkus.native.container-build=true`).
> Use macOS M1 runner to build arm64 binaries

- .github/workflows/_build-native-meta.yml
Apparently Docker is not available on the M1 runner due to nested virtualization not being supported: https://github.com/orgs/community/discussions/69211#discussioncomment-7197681
This reverts commit 525cebea27959a7dc1690c9db804d379cc545042.
> Revert "Use macOS M1 runner to build arm64 binaries"

- commons-persistence/src/main/java/org/dependencytrack/persistence/model/NotificationRule.java
While DataNucleus can automatically map `null` database values to the primitive value `false`, Hibernate can't, and throws an exception instead.
Because existing deployments will not have a value for the `LOG_SUCCESSFUL_PUBLISH` column, exceptions will be thrown for those records.
> Fix Hibernate exception due to `null` being assigned to primitive `boolean`

- scripts/change-user-pass.sh
- scripts/upload-boms.sh
* `change-user-pass.sh` can be used to perform the initial password change without having to open the frontend
* `upload-boms.sh` automatically authenticates and uploads all BOMs in a specified directory; Very simplistic for now, it literally just dumps all BOMs as quick as it can
Note, `upload-boms.sh` currently fails to authenticate due to https://github.com/stevespringett/Alpine/pull/542.
For quick, local testing, setting up API keys is too much hassle.
> Add some simple helper scripts

- commons-persistence/src/main/java/org/dependencytrack/persistence/repository/VulnerableSoftwareRepository.java
- vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/scanner/internal/InternalScannerProcessor.java
- vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/processor/scanner/internal/InternalScannerProcessorTest.java
Ports https://github.com/DependencyTrack/dependency-track/pull/3209 from DT v4.10.0
Relates to https://github.com/DependencyTrack/hyades/issues/983
> Fix false positives in CPE matching due to ambiguous vendor/product relations

- e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
Unless explicit sorting is applied, it's up to the database to decide in which order records are being returned.
This fixes the e2e test failure observed in https://github.com/DependencyTrack/hyades/actions/runs/8077647349/job/22068521065
> Don't assert order of findings returned by REST API in e2e test

- vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/retry/RetryableRecord.java
- vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/scanner/ossindex/OssIndexProcessor.java
- vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/scanner/snyk/SnykProcessor.java
- vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/processor/retry/RetryableRecordTest.java
Also format Protobuf record keys and values as JSON when logging them; The default `toString()` output of Protobuf messages contains lots of unnecessary whitespace.
Example output:
```
Encountered retryable exception while analyzing RetryableRecord{key=pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.49, value={"key":{"scanToken":"dee932c1-fe98-4197-9bcd-21646f910727","componentUuid":"e310ebc2-904e-45e6-ac82-49e8081e3db0"},"scanner":"SCANNER_SNYK","component":{"uuid":"e310ebc2-904e-45e6-ac82-49e8081e3db0","purl":"pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.49?foo\u003dbar\u0026type\u003djar"}}, timestamp=1709127126459, headers=RecordHeaders(headers = [], isReadOnly = false), nextRetryAt=1709127131153, retryAttempts=1}: HTTP 500 Internal Server Error
```
> Emit logs as `WARN` when encountering retryable exceptions

- commons/pom.xml
- commons/src/test/java/org/dependencytrack/common/HttpClientTests.java
- commons/src/test/java/org/dependencytrack/util/WireMockTestResource.java
- repository-meta-analyzer/pom.xml
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/RepositoryMetaAnalyzerIT.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/processor/MetaAnalyzerProcessorTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/ComposerMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/CpanMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/GemMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/GoModulesMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/HexMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/MavenMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NpmMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/PypiMetaAnalyzerTest.java
Closes https://github.com/DependencyTrack/hyades/issues/993
> removed usage of mockserver

- .github/workflows/_build-native-meta.yml
- .github/workflows/ci.yml
- .github/workflows/publishJar.yml
- .github/workflows/release.yml
By disabling reporting of download status for dependencies. These horribly pollute build logs.
> Reduce verbosity of Maven in CI

- vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdx.java
- vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/processor/scanner/snyk/SnykProcessorTest.java
- vulnerability-analyzer/src/test/resources/snyk/duplicate-issues-response.json
We're occasionally seeing responses from Snyk that contain the exact same issue multiple times. It is unclear where those are coming from, but in any case we shouldn't forward obvious duplicates to the API server.
> Handle duplicate issues reported by Snyk

- docker-compose.yml
This is mostly for local development purposes and / or demo setups. Installing OpenSSL can be problematic for folks behind corporate proxies. Using `/dev/urandom` should be sufficient considering that's what `openssl rand` is using behind the scenes anyway.
> Use `/dev/urandom` instead of `openssl rand` to generate secret key

- e2e/pom.xml
- e2e/src/main/java/org/dependencytrack/apiserver/ApiServerAuthInterceptor.java
- e2e/src/main/java/org/dependencytrack/apiserver/ApiServerClient.java
- e2e/src/main/java/org/dependencytrack/apiserver/CompositeDecoder.java
- e2e/src/main/java/org/dependencytrack/apiserver/CompositeEncoder.java
- e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
- pom.xml
As of Quarkus 3.9.x(?), the RestClient can no longer be used without an CDI context being present. This is causing test failures, e.g. https://github.com/DependencyTrack/hyades/actions/runs/8535995179/job/23383687429
```
java.lang.IllegalStateException: The Reactive REST Client needs to be built within the context of a Quarkus application with a valid ArC (CDI) context running.
```
This replaces the Quarkus RestClient with OpenFeign (https://github.com/OpenFeign/feign), which is largely compatible, although requiring a few customizations when it comes to encoding and decoding.
> Fix broken e2e tests due to Quarkus RestClient requiring CDI context

- e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
Fixes the currently broken `VulnerabilityPolicyE2ET` e2e test, caused by an assertion for an invalid exception.
N/A
As of https://github.com/DependencyTrack/hyades/pull/1170, `apiServerClient` no longer throws `WebApplicationException`s.
> Fix broken assertion in e2e test

- mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
- mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java
- mirror-service/src/test/resources/datasource/nvd/cve-vuln.json
- pom.xml
Fixes mapping of CPEs to vers ranges when version is NA (`-`).
* Move creation of Component record with CPE *before* constructing the version range. This way we won't be dropping CPE data even when version range construction fails.
* Handle cases where `versFromNvdRange` doesn't yield a range.
* Log exceptions during vers constructions as warning instead of as debug message, to make it more obvious when things are not working as expected.
Fixes #1179
N/A
- ~This PR introduces new or alters …
> Fix mapping of CPEs to vers ranges when version is NA (`-`)

- monitoring/grafana/dashboards/apiserver_dashboard.json
> [!WARNING]
> Depends on https://github.com/DependencyTrack/hyades-apiserver/pull/553
> Update API server dashboard to use Parallel Consumer metric for mirror processing duration

- .github/workflows/deploy-docs.yml
Currently the documentation for `0.5.0-SNAPSHOT` is aliased as `latest`, which results in users seeing docs that are not applicable to the current stable version.
With this change, the `latest` alias will only be applied when building for a non-`SNAPSHOT` version.
N/A
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the …
> Don't label docs for `SNAPSHOT` versions as `latest`

- monitoring/grafana/dashboards/apiserver_dashboard.json
Leverages histograms to calculate p99, p95, p90, p75, and p50 percentiles of event processing durations.
> [!NOTE]
> ~Based on https://github.com/DependencyTrack/hyades/pull/1166, metrics for the new processors are already included. Will rebase this PR once #1166 is merged.~
> [!WARNING]
> Depends on https://github.com/DependencyTrack/hyades-apiserver/pull/652
N/A
- ~This PR introduces new or alters …
> Display percentiles for event processing durations on Grafana dashboard

- commons/pom.xml
- commons/src/main/java/org/dependencytrack/commonutil/DateUtil.java
- repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/CargoMetaAnalyzer.java
- repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/RepositoryAnalyzerFactory.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/CargoMetaAnalyzerTest.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/RepositoryAnalyzerFactoryTest.java
- Porting issue to add Cargo analyzer: https://github.com/DependencyTrack/dependency-track/pull/3511
- Added the `CargoMetaAnalyzer.java`, which was not there. Made changes to the file to fit hyades changes
- Added `fromISO8601` function to `DateUtil.java`. ~~Note: my IDE says that `javax.xml.bind` cannot be resolved, but maybe I don't have the environment configured. Is this dependency added to this project able to be used?~~
- switched from javax to jakarta https://jakarta.ee/specifications/platform/9/apidocs/jakarta/xml/bind/datatypeconverter 
Porting changes from 4.11: https://github.com/DependencyTrack/hyades/issues/1190
I haven't run any manual tests for this feature either. I can look into doing so if needed
> porting issue-3511 adding cargo analyzer

- repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzer.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzerTest.java
Nuget Analyzer has list of two supported SimpleDateFormat which are allowed for parsing the dates being received from the repository, based on limited test data.
Now, as seen in logs, below date format is also received from the nugget repo. This date has offset dateTime and needs to be added to the list of supported formats in order to avoid the ParseException.
Date example: 1900-01-01T00:00:00+00:00
Format needed: yyyy-MM-dd'T'HH:mm:ss
Closes https://github.com/DependencyTrack/hyades/issues/1263
> Add date format to support offset in nuget analyser

- mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
- mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
Fixes inconsistent `source` identifier for GitHub Advisories.
Fixes #1295
N/A
> Fix inconsistent `source` identifier for GitHub Advisories

- notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
- notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisherConfig.java
- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
porting issue https://github.com/DependencyTrack/dependency-track/pull/3422 
for porting issues https://github.com/DependencyTrack/hyades/issues/1190 
need to port corresponding front end issue too https://github.com/DependencyTrack/frontend/pull/720
> Port: Configurable email subject prefix 

- repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/AbstractMetaAnalyzer.java
- repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/NpmMetaAnalyzer.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NpmMetaAnalyzerTest.java
Fixes URISyntaxExceptions during repository metadata analysis, when NPM PURLs contain special characters.
Backport change https://github.com/DependencyTrack/hyades/issues/1190
> Port fix for npm purls with special characters

- e2e/src/test/java/org/dependencytrack/e2e/BomProcessedNotificationDelayedE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/BomUploadProcessingE2ET.java
- e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
Fixes CVSS vectors missing from e2e notification asserts.
Vectors were added to notification subjects in https://github.com/DependencyTrack/hyades-apiserver/pull/696.
Depends on https://github.com/DependencyTrack/hyades-apiserver/pull/699
N/A
N/A
> Fix CVSS vectors missing from e2e notification asserts

- commons-persistence/src/main/resources/schema.sql
Applies schema changes from https://github.com/DependencyTrack/hyades-apiserver/pull/706 to `schema.sql`.
Relates to https://github.com/DependencyTrack/hyades/issues/1190
Caused by https://github.com/DependencyTrack/hyades-apiserver/pull/706
N/A
> Apply schema changes from https://github.com/DependencyTrack/hyades-apiserver/pull/706

- e2e/src/main/java/org/dependencytrack/apiserver/ApiServerClient.java
- e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
Fixes e2e tests failing to get API keys.
As of https://github.com/DependencyTrack/hyades-apiserver/pull/725, API keys are no longer created automatically when creating teams.
Adds a request to explicitly create a key.
N/A
N/A
> Fix e2e tests failing to get API keys

- commons-kstreams/src/main/java/org/dependencytrack/kstreams/statestore/StateStoreUtil.java
- commons-kstreams/src/test/java/org/dependencytrack/kstreams/statestore/StateStoreUtilTest.java
- docs/reference/topics.md
- scripts/create-topics.sh
We currently set [max.compaction.lag.ms](https://kafka.apache.org/37/generated/topic_config.html#topicconfigs_max.compaction.lag.ms) to 0 for compacted topics. This works for Redpanda, but fails for Apache Kafka.
The allowed range for max.compaction.lag.ms is [1,...], with the default value being 9223372036854775807.
Fix the same.
Closes https://github.com/DependencyTrack/hyades/issues/1391
> Fix max.compaction.lag.ms to make it compatible with Apache Kafka

- commons/src/main/java/org/dependencytrack/common/KafkaTopic.java
- commons/src/test/java/org/dependencytrack/common/KafkaTopicTest.java
- docs/reference/configuration/api-server.md
- docs/reference/configuration/mirror-service.md
- docs/reference/configuration/overview.md
- docs/reference/configuration/repo-meta-analyzer.md
- mirror-service/src/main/resources/application.properties
- notification-publisher/src/main/java/org/dependencytrack/notification/config/ParallelConsumerConfiguration.java
- notification-publisher/src/main/resources/application.properties
- repository-meta-analyzer/src/main/resources/application.properties
- scripts/create-topics.sh
- vulnerability-analyzer/src/main/resources/application.properties
Creation of Kafka Streams repartition topics currently fails with `Unknown topic config name: prefix`, when using Apache Kafka instead of Redpanda. 
Rename the prefix config to avoid the error.
Closes https://github.com/DependencyTrack/hyades/issues/1392
> Rename kafka topic prefix for apache kafka compatibility

- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
- notification-publisher/src/test/resources/templates/email.peb
Fixes the project URL for new vulnerabilities in email peb.
Backport change : https://github.com/DependencyTrack/hyades/issues/1358
> Port : Fix project link for new vulnerable dependency for email

- docker-compose.yml
Adds initializer container to Docker Compose.
The initializer executes schema migrations and populates the database with default objects. We added it to the Helm chart already (see https://github.com/DependencyTrack/helm-charts/issues/136), but it was still missing from `docker-compose.yml`.
The benefit of this addition is that we avoid any schema-related errors in hyades services, and the API server executing migrations and default object population on every startup.
N/A
N/A …
> Add initializer container to Docker Compose

- .github/workflows/build-native-mirror-service.yml
Fixes native `mirror-service` not being built upon change in `commons-persistence`
`mirror-service` originally didn't require database access, so we didn't trigger a build when persistence code changed. This has since changed, causing issues like #1517.
Fixes #1517 …
> Fix native `mirror-service` not being built upon change in `commons-persistence`

- docker-compose.yml
- e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
As per JDBC driver documentation (https://jdbc.postgresql.org/documentation/use/):
This will change batch inserts from insert into foo (col1, col2, col3) values (1, 2, 3) into insert into foo (col1, col2, col3) values (1, 2, 3), (4, 5, 6) this provides 2-3x performance improvement
Indeed, per default even batched JDBC statements are executed one-by-one, somewhat defeating the purpose of batching in the first place. This option allows us to get the true benefit out of performing batch operations.
N/A
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the …
> Enable `reWriteBatchedInserts` Postgres JDBC driver option in e2e tests

- repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzer.java
- repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzerTest.java
This PR addressed the issue of pre-release nuget packages being returned as the latest version.
The [Nuget Documentation](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#pre-release-versions) identifies packages with a "-" in their version string as a pre-release package.
The change is to filter the list of Nuget Packages that contain an "-" when determining the latestVersion. If the component being inspected is a pre-release itself, then pre-release versions are not filtered.
Port change : https://github.com/DependencyTrack/hyades/issues/1358 …
> Port : Exclude pre-releases from NuGet latest version check

- pom.xml
- repository-meta-analyzer/pom.xml
Replaces `github-api` with `quarkus-github-api` extension.
The Quarkus extension wraps the library, and takes care of making it compatible with native image.
Native image builds started failing with https://github.com/DependencyTrack/hyades/pull/1515
Closes #1515
N/A
[documentation]: …
> Replace `github-api` with `quarkus-github-api` extension

- mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
- mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java
- mirror-service/src/test/resources/datasource/nvd/cve-2024-23113.json
Fixes CPE matching for NVD mirroring.
Port change https://github.com/DependencyTrack/hyades/issues/1358
> Port : Fix CPE matching for NVD mirroring via REST API

- pom.xml
Bumps Quarkus to 3.17.8.
N/A
Dependabot raised a PR for Quarkus 3.18 (https://github.com/DependencyTrack/hyades/pull/1634), but tests are failing and 3.18 was not officially announced yet. Playing it safe and moving to the next bugfix version first.
[documentation]: https://dependencytrack.github.io/hyades/latest/development/docu …
> Bump Quarkus to 3.17.8

- docs/architecture/decisions/000-index.md
- docs/architecture/decisions/001-drop-kafka-dependency.md
- docs/architecture/decisions/002-workflow-orchestration.md
- docs/architecture/decisions/003-notification-publishing.md
- docs/architecture/decisions/004-file-storage-plugin.md
- mkdocs.yml
* Adds "ADR-001: Drop Kafka Dependency"
* Adds "ADR-002: Workflow Orchestration"
* Adds "ADR-003: Notification Publishing"
* Adds "ADR-004: File Storage Plugin"
N/A
Refer to the ADRs' contents for details. …
> Add ADRs for dropping dependency on Kafka

- pom.xml
Types for `modifiedSubAvailabilityImpact`, `modifiedSubIntegrityImpact`, and `modifiedSubConfidentialityImpact` have been changed in the new version. 
Upgrade the version to avoid `NvdApiException`.
https://github.com/jeremylong/open-vulnerability-clients/releases/tag/v7.2.2
N/A
> Bump open-vulnerability-clients version

- notification-publisher/src/main/java/org/dependencytrack/notification/config/PebbleConfiguration.java
- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/CsWebexPublisherTest.java
- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
- notification-publisher/src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
- pom.xml
Disables `include` tag for Pebble templates.
Fixes https://github.com/DependencyTrack/dependency-track/security/advisories/GHSA-9582-88hr-54w3
Ports https://github.com/DependencyTrack/dependency-track/pull/4684
N/A
> Port: Disable `include` tag for Pebble templates

- docs/architecture/decisions/004-file-storage-plugin.md
Updates ADR-004 to include file media type and SHA-256 digest.
Transmitting the media type avoids redundant file type detection.
Explicit inclusion of the SHA-256 digest field is a consequence of it being common across all storage providers. Storing it in a generic metadata field is complicating things unnecessarily.
N/A
N/A …
> Update ADR-004 to include file media type and SHA-256 digest

- docs/getting-started/changes-over-v4.md
Document the breaking changes in Findings response object and SARIF document.
Respective changes in apiserver: https://github.com/DependencyTrack/hyades-apiserver/pull/1090 
Issue: https://github.com/DependencyTrack/hyades/issues/1678
> Issue-1090 : Document Findings response changes.

- commons-persistence/src/test/resources/application.properties
- docs/getting-started/upgrading.md
- docs/operations/database.md
- e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
- mirror-service/src/main/resources/application.properties
- notification-publisher/src/main/resources/application.properties
- repository-meta-analyzer/src/main/resources/application.properties
- vulnerability-analyzer/src/main/resources/application.properties
Raises minimum supported PostgreSQL version to 13.
Also ensures that tests are executed against this minimum supported version.
Closes #1724
N/A
> Raise minimum supported PostgreSQL version to 13

- docs/getting-started/changes-over-v4.md
Pagination was already supported by `findings` REST endpoints `/api/v1/finding` and /api/v1/finding/grouped.
Now, it has been added to endpoint `/api/v1/finding/project/{uuid}` as well.
Document the same.
https://github.com/DependencyTrack/hyades/issues/1708
Backend : https://github.com/DependencyTrack/hyades-apiserver/pull/1111
> Document pagination support for `findings` REST endpoint

- commons-persistence/src/main/resources/schema.sql
Update schema for new `severity` enum type.
https://github.com/DependencyTrack/hyades/issues/1725
Apiserver: https://github.com/DependencyTrack/hyades-apiserver/pull/1122
> Update schema for new `severity` enum type

- mkdocs.yml
Adding the correct path to Role Documentation to mkdocs.yml. 
> fix: Add Correct Path for Role Documenation

- vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/util/ProcessorUtils.java
Consider `TimeoutException` to be retryable.
When the Quarkus HTTP client fails due to a timeout, it doesn't throw a `ConnectTimeoutException` or `SocketTimeoutException`, but a vert.x exception that inherits from `TimeoutException`.
N/A
N/A
[migration changelog]: https://dependencytrack.github.io/hyades/latest/development/data …
> Consider `TimeoutException` to be retryable

- vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/misc/ScannerResultAggregator.java
Enforces punctuation latency ceiling for scanner result aggregator.
Continuation of https://github.com/DependencyTrack/hyades/pull/1841, which addressed the `TombstoneEmittingProcessor`.
N/A
N/A
> Enforce punctuation latency ceiling for scanner result aggregator
