DependencyTrack/hyades

src/main/java/org/acme/tasks/scanners/BaseComponentAnalyzerTask.java
src/main/java/org/acme/tasks/scanners/OssIndexAnalysisTask.java
src/main/java/org/acme/tasks/scanners/SnykAnalysisTask.java

Fixed the Snyk analyzer so the good case works for now. We should probably migrate some of the changes we introduced to vanilla DT back into this analyzer so they work roughly the same way.

Fix snyk analyzer

---

README.md
src/main/java/org/acme/util/SecretsUtil.java

Signed-off-by: mehab <meha.bhargava2@gmail.com>
Usage of externally generated secret key added and updated readme for explaining usage. Will become useful once we can access the DT database to get encrypted secrets and use this code to decrypt the same.

externalized secret generation and usage added.

---

DEMO.md
docker-compose.yml

Clarify some details in `DEMO.md`

---

.github/workflows/publish.yml

So the images run smooth on M1/M2 Macs as well 🧑‍💻

Build and publish multi-platform container images

---

.github/workflows/ci.yml
pom.xml

Perform sonar analysis in CI workflow

---

notification-publisher/pom.xml
pom.xml
vulnerability-analyzer/pom.xml
vulnerability-analyzer/src/main/java/org/acme/analyzer/SnykAnalyzer.java
vulnerability-analyzer/src/main/java/org/acme/analyzer/SnykAnalyzerConfig.java
vulnerability-analyzer/src/test/java/org/acme/analyzer/SnykAnalyzerTest.java
vulnerability-analyzer/src/test/java/org/acme/client/snyk/SnykClientTest.java
vulnerability-analyzer/src/test/resources/snyk/multiple-issues-response.json
vulnerability-analyzer/src/test/resources/snyk/no-issues-response.json
vulnerability-analyzer/src/test/resources/snyk/one-issue-response.json

Add more tests for SnykAnalyzer and SnykClient

---

README.md

Add build status and Sonar metrics badges

---

commons/pom.xml
commons/src/main/java/org/acme/common/CircuitBreakerCustom.java
commons/src/test/java/org/acme/common/CircuitBreakerCustomTest.java
vulnerability-analyzer/src/main/java/org/acme/analyzer/OssIndexAnalyzer.java
vulnerability-analyzer/src/main/java/org/acme/analyzer/SnykAnalyzer.java
vulnerability-analyzer/src/test/java/org/acme/analyzer/SnykAnalyzerTest.java

https://github.com/mehab/DTKafkaPOC/issues/126

Issue-126 : Circuit breaker for snyk and oss clients

---

.github/workflows/publishNativeBinary.yml

Use GH Action to build and push container image in one step

---

vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessor.java
vulnerability-analyzer/src/test/java/org/acme/processor/snyk/SnykProcessorTest.java

No point in wasting resources and API rate limit quota for requests that can never succeed.

Snyk: skip unsupported PURL types

---

.github/workflows/publishJar.yml
mirror-service/pom.xml

Until https://github.com/quarkusio/quarkus/issues/30424 is fixed

Workaround for buildx build failures

---

mirror-service/src/main/docker/Dockerfile.jvm
mirror-service/src/main/docker/Dockerfile.legacy-jar
mirror-service/src/main/docker/Dockerfile.native
mirror-service/src/main/docker/Dockerfile.native-micro

Add missing Dockerfiles for mirror-service

---

commons/pom.xml
commons/src/main/java/org/acme/model/Cwe.java
commons/src/main/java/org/acme/model/NotificationRule.java
commons/src/main/java/org/acme/model/Project.java
commons/src/main/java/org/acme/model/Tag.java
commons/src/main/java/org/acme/model/VulnerabilityAlias.java
commons/src/main/java/org/acme/persistence/CollectionIntegerConverter.java
commons/src/main/java/org/acme/persistence/CweImporter.java
notification-publisher/src/main/java/org/acme/notification/publisher/AbstractWebhookPublisher.java
notification-publisher/src/main/java/org/acme/notification/publisher/ConsolePublisher.java
notification-publisher/src/main/java/org/acme/notification/publisher/Publisher.java
notification-publisher/src/main/java/org/acme/notification/publisher/SendMailPublisher.java
pom.xml
repository-meta-analyzer/src/main/java/org/acme/repositories/AbstractMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/acme/repositories/ComposerMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/acme/repositories/GemMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/acme/repositories/GoModulesMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/acme/repositories/HexMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/acme/repositories/MavenMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/acme/repositories/NpmMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/acme/repositories/NugetMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/acme/repositories/PypiMetaAnalyzer.java

Remove last traces of Alpine

---

.kodiak.toml

Signed-off-by: mehab <meha.bhargava2@gmail.com>

added required label

---

.github/workflows/_build-native-meta.yml
.github/workflows/publishJar.yml

Fix container image repo name; Do not push on forks

---

mirror-service/pom.xml
mirror-service/src/main/resources/application.properties
pom.xml

Fix broken native image build of mirror-service

---

.github/workflows/_build-native-meta.yml
.github/workflows/build-native-mirror-service.yml
mirror-service/src/main/resources/application.properties

Fix Kafka compression not working in native image

---

mirror-service/src/main/java/org/hyades/cyclonedx/CycloneDxReflectionConfiguration.java
mirror-service/src/main/java/org/hyades/nvd/NvdReflectionConfiguration.java

Register `cyclonedx-core-java` and `nvd-lib` model classes for reflection

---

LICENSE

Add `LICENSE`

---

vulnerability-analyzer/src/main/java/org/hyades/client/snyk/AuthorizationClientHeaderFactory.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/Coordinate.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/Issue.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/ReportRequest.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/Representation.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/SnykClient.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/SnykClientConfiguration.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/SnykService.java
vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessor.java
vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessorSupplier.java
vulnerability-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/AuthorizationClientHeaderFactoryTest.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/ModelConverterTest.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/SnykClientTest.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/SnykServiceTest.java
vulnerability-analyzer/src/test/java/org/hyades/processor/snyk/SnykProcessorTest.java
vulnerability-analyzer/src/test/resources/snyk/multiple-issues-batch-response.json

Signed-off-by: vithikashukla <vithika.shukla14@gmail.com>
In this PR, only new client, corresponding model classes and tests have been updated of batch processing api. Renamed old SnylClient class to SnykService which will be removed in next PR when processor has been updated. Reason for doing it this way is to keep PR small in size. Once this PR is merged, there will be follow up PR to update processor

First part of using batch processign api

---

.github/workflows/ci.yml
pom.xml

Signed-off-by: Niklas <nscuro@protonmail.com>

Re-enable SonarCloud

---

CONFIGURATION.md
vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessor.java

Signed-off-by: vithikashukla <vithika.shukla14@gmail.com>
Small PR for adding a couple of properties in configuration.md and move an incorrect logger

Added snyk properties in configuration.md

---

vulnerability-analyzer/src/main/java/org/hyades/client/snyk/AuthorizationClientHeaderFactory.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/SnykClient.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/AuthorizationClientHeaderFactoryTest.java

Signed-off-by: vithikashukla <vithika.shukla14@gmail.com>

added appropriate content type header

---

monitoring/grafana/dashboards/vuln-analyzer_dashboard.json
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/SnykClientConfiguration.java

MR has 2 minor changes : 
1. Removed configuration snykHttpClient config bean as it was not required anymore
2. Scanner names have been changed to class names

Removed snykHttpClient bean

---

metrics-service/src/main/resources/application.properties

Add prefix

---

.github/dependabot.yml
.github/workflows/build-native-metrics-service.yml
.github/workflows/ci.yml
docker-compose.yml
metrics-service/src/main/resources/application.properties

Added native image build and test stage for metric service and modified the docker compose file

Add native workflow for metrics service

---

metrics-service/src/main/resources/application.properties
metrics-service/src/test/java/org/hyades/MetricsServiceIT.java

Addresses issue https://github.com/DependencyTrack/hyades/issues/370
Added integration test

Add integration test

---

notification-publisher/src/main/resources/application.properties
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Removed sql logging by hibernate in dev mode as well

remove hibernate sql logging in dev mode as well

---

docker-compose.yml
metrics-service/pom.xml
metrics-service/src/main/java/org/hyades/metrics/model/Metrics.java
metrics-service/src/main/java/org/hyades/metrics/model/PortfolioMetrics.java
metrics-service/src/main/java/org/hyades/metrics/model/ProjectMetrics.java
metrics-service/src/main/java/org/hyades/metrics/model/VulnerabilityStatus.java
metrics-service/src/main/java/org/hyades/metrics/processor/ComponentDeltaProcessor.java
metrics-service/src/main/java/org/hyades/metrics/processor/ProjectDeltaProcessor.java
metrics-service/src/test/java/org/hyades/metrics/model/PortfolioMetricsTest.java
metrics-service/src/test/java/org/hyades/metrics/model/ProjectMetricsTest.java
metrics-service/src/test/java/org/hyades/metrics/processor/ComponentDeltaProcessorTest.java
metrics-service/src/test/java/org/hyades/metrics/processor/DeltaProcessorConfigurationInMemory.java
metrics-service/src/test/java/org/hyades/metrics/processor/ProjectDeltaProcessorTest.java
monitoring/grafana/dashboards/metrics-service_dashboard.json
monitoring/prometheus.yml

Fixed https://github.com/DependencyTrack/hyades/issues/368 and added dashboard

Fix vulnerability project count and add dashboard

---

mirror-service/src/main/java/org/hyades/client/NvdClient.java
mirror-service/src/main/java/org/hyades/client/NvdClientConfig.java

Fixed epoch issue and removed object creation for static method

Fixed epoch issue

---

vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/snyk/SnykProcessor.java
vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/snyk/SnykProcessorTest.java
vulnerability-analyzer/src/test/resources/snyk/different-purl-casing-response.json

Fix PURL casing mismatches for Snyk

---

vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/snyk/SnykProcessor.java
vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/snyk/SnykProcessorTest.java

Do not expect an explicit result for every submitted PURL from Snyk

---

e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
notification-publisher/src/main/java/org/hyades/notification/NotificationRouter.java
notification-publisher/src/test/java/org/hyades/notification/NotificationRouterTest.java
proto/src/main/proto/org/hyades/notification/v1/notification.proto

Use back references instead of including all affected projects in notification subject

---

proto/src/main/proto/org/hyades/vuln/v1/vuln.proto
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/ModelConverter.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/Remedy.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/Slots.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/ModelConverterTest.java

Mapping for publication time of vulnerability is missing while paring Snyk results.
Added the missing mapping.
https://github.com/DependencyTrack/hyades/issues/374 -> Enhancement

Map SNYK publication time and remedies

---

vulnerability-analyzer/src/main/java/org/hyades/client/snyk/AuthorizationClientHeaderFactory.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/AuthorizationClientHeaderFactoryTest.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/ModelConverterTest.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/SnykClientTest.java

Enhancement added from https://github.com/DependencyTrack/dependency-track/pull/2396
Tested and works with batch api as well

backported enhancement from 2396

---

repository-meta-analyzer/src/main/java/org/hyades/model/MetaAnalyzerException.java
repository-meta-analyzer/src/main/java/org/hyades/repositories/ComposerMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/hyades/repositories/GemMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/hyades/repositories/GoModulesMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/hyades/repositories/HexMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/hyades/repositories/IMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/hyades/repositories/MavenMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/hyades/repositories/NpmMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/hyades/repositories/NugetMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/hyades/repositories/PypiMetaAnalyzer.java

An unique and specific exception MetaAnalyzerException for repository metadata fetch unhandled issues.
https://github.com/DependencyTrack/hyades/issues/374

Better handling of repository meta analysers errors

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
SECURITY.md

Simply copied from upstream Dependency-Track for now.

Add `CODE_OF_CONDUCT.md`, `CONTRIBUTING.md`, and `SECURITY.md`

---

docker-compose.yml
monitoring/grafana/dashboards/apiserver_dashboard.json

... to include information about Kafka clients, as well as some functional metrics regarding event processing durations.

Update API server Grafana dashboard

---

TOPICS.md

Also document co-partitioning requirements

`TOPICS.md`: Specify compaction for changelog topics

---

mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
mirror-service/src/test/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java

Issue: https://github.com/DependencyTrack/hyades/issues/486

Replace cpe with generic as versioning scheme in NVD parser

---

notification-publisher/src/main/java/org/hyades/notification/publisher/SendMailPublisher.java
notification-publisher/src/test/java/org/hyades/notification/publisher/SendMailPublisherTest.java

Issue: https://github.com/DependencyTrack/hyades/issues/561

Fix NPE for email alerts

---

vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/internal/InternalScannerProcessor.java
vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/internal/InternalScannerProcessorSupplier.java
vulnerability-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/internal/InternalScannerProcessorTest.java

Removed internal cache and increased the ttl of cache entries to 4 hours

removed internal cache and increased ttl for snyk and ossindex entries

---

commons/pom.xml
commons/src/main/java/org/hyades/common/metrics/ExtraJvmMetricsBinder.java
pom.xml

Analog to https://github.com/DependencyTrack/hyades-apiserver/pull/168

Capture physical allocated memory (RSS) of the JVM process

---

mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
mirror-service/src/main/java/org/hyades/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
mirror-service/src/test/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java
mirror-service/src/test/java/org/hyades/vulnmirror/datasource/osv/OsvToCyclonedxParserTest.java
mirror-service/src/test/resources/datasource/nvd/cve-vuln.json

Changes per comment on PR -> https://github.com/DependencyTrack/hyades-apiserver/pull/171#discussion_r1204092656

Refactor affected range parsing

---

notification-publisher/src/main/java/org/hyades/notification/publisher/AbstractWebhookPublisher.java

Fixing left over open httpresponse

using try with resources on httpclient

---

proto/src/main/proto/org/hyades/notification/v1/notification.proto

Addresses : https://github.com/DependencyTrack/hyades/pull/613

renamed variable for better semantics of json result

---

vulnerability-analyzer/src/main/java/org/hyades/client/snyk/RestClientExceptionMapper.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/SnykClientTest.java

Include Snyk request ID in exception message

---

mirror-service/src/main/java/org/hyades/vulnmirror/datasource/AbstractDatasourceMirror.java
mirror-service/src/main/resources/application.properties
mirror-service/src/test/java/org/hyades/vulnmirror/KafkaStreamsTopologyIT.java
notification-publisher/src/main/java/org/hyades/notification/config/ProtoReflectionConfiguration.java
proto/src/main/java/org/hyades/proto/KafkaProtobufSerializer.java
proto/src/test/java/org/hyades/proto/KafkaProtobufSerdeTest.java

Reverts DependencyTrack/hyades#628

Revert "Fix native image tests for mirror-service"

---

commons-persistence/src/main/java/org/hyades/persistence/repository/RepoEntityRepository.java

replaced call to QueryHints.HINT_READONLY with HibernateHints.HINT_READ_ONLY

Replace deprecated call

---

vulnerability-analyzer/src/main/java/org/hyades/client/snyk/ModelConverterToCdx.java
vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/snyk/SnykProcessor.java
vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/snyk/SnykProcessorTest.java

Fix Snyk reporting unrelated vulnerabilities

---

docs/design/01-workflow-state-tracking.md

So it can be revisited and reviewed without going through loads of issues.
Closes #664

Decouple design docs from #664 into markdown file

---

mirror-service/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
mirror-service/src/main/java/org/hyades/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
mirror-service/src/test/java/org/hyades/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
vulnerability-analyzer/src/main/java/org/hyades/client/ossindex/ModelConverterToCdx.java
vulnerability-analyzer/src/main/java/org/hyades/client/snyk/ModelConverterToCdx.java
vulnerability-analyzer/src/test/java/org/hyades/client/snyk/ModelConverterToCdxTest.java

Fixes https://github.com/DependencyTrack/hyades/issues/719

Fix precision of CVSS scores

---

e2e/src/test/java/org/hyades/e2e/BomProcessedNotificationDelayedE2ET.java
e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
proto/src/main/proto/org/hyades/notification/v1/notification.proto

Issue: https://github.com/DependencyTrack/hyades/issues/782
Apiserver changes: https://github.com/DependencyTrack/hyades-apiserver/pull/310

Added correlation token in notification subjects

---

commons-kstreams/pom.xml
commons-persistence/pom.xml
commons/pom.xml
e2e/pom.xml
mirror-service/pom.xml
notification-publisher/pom.xml
pom.xml
proto/pom.xml
repository-meta-analyzer/pom.xml
vulnerability-analyzer/pom.xml

Previous release was 0.1.4. Moving to 0.1.5 now

version bump

---

commons-persistence/pom.xml
pom.xml

Ported from https://github.com/DependencyTrack/dependency-track/pull/2651 and https://github.com/DependencyTrack/dependency-track/pull/3102

Include Cloud SQL database connector for PostgreSQL

---

commons-persistence/src/main/java/org/dependencytrack/persistence/repository/ConfigPropertyRepository.java
commons-persistence/src/main/java/org/dependencytrack/persistence/repository/NotificationRuleRepository.java
commons-persistence/src/main/java/org/dependencytrack/persistence/repository/RepoEntityRepository.java
commons-persistence/src/main/java/org/dependencytrack/persistence/repository/TeamRepository.java
commons-persistence/src/main/java/org/dependencytrack/persistence/repository/UserRepository.java
commons-persistence/src/main/java/org/dependencytrack/persistence/repository/VulnerableSoftwareRepository.java
commons-persistence/src/test/java/org/dependencytrack/persistence/repository/NotificationRuleRepositoryTest.java
notification-publisher/src/main/java/org/dependencytrack/notification/NotificationRouter.java
notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterTest.java

Fixes a bug where `NotificationRule`s were not checked for whether they're enabled.
The existing test for this did use incorrect test inputs, effectively not testing the desired functionality.

Fix missing check for `NotificationRule` enablement

---

docker-compose.yml
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
mirror-service/src/main/resources/application.properties
notification-publisher/src/main/resources/application.properties
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Bump Redpanda to `v23.2.21`

---

commons-persistence/src/main/java/org/dependencytrack/persistence/model/RepositoryType.java
commons-persistence/src/test/java/org/dependencytrack/persistence/model/RepositoryTypeTest.java
repository-meta-analyzer/pom.xml
repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/GithubMetaAnalyzer.java
repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/GitHubMetaAnalyzerTest.java

https://github.com/DependencyTrack/hyades/issues/983

Add support for github meta analyzer

---

notification-publisher/src/main/java/org/dependencytrack/notification/NotificationRouter.java
notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/GithubMetaAnalyzer.java
repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/GitHubMetaAnalyzerTest.java

https://github.com/DependencyTrack/hyades/issues/983
- https://github.com/DependencyTrack/dependency-track/pull/3315
- https://github.com/DependencyTrack/dependency-track/pull/3306
- https://github.com/DependencyTrack/dependency-track/pull/3246

Backport minor bug fixes

---

.github/workflows/_build-native-meta.yml
.github/workflows/ci.yml
.github/workflows/publishJar.yml
.github/workflows/release.yml
mirror-service/src/main/docker/Dockerfile.jvm
notification-publisher/src/main/docker/Dockerfile.jvm
repository-meta-analyzer/src/main/docker/Dockerfile.jvm
vulnerability-analyzer/src/main/docker/Dockerfile.jvm

Relates to https://github.com/DependencyTrack/hyades/issues/1070

Bump container base images to Java 21, and build against Java 21 in CI

---

README.md
pom.xml

> [!NOTE]
> This PR is based on #1095
Relates to https://github.com/DependencyTrack/hyades/issues/1070

Raise baseline Java version to 21

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/defect-report.yml
.github/ISSUE_TEMPLATE/enhancement-request.yml
.github/PULL_REQUEST_TEMPLATE.md

To have more structure for issues and PRs, setup templates for them.
Closes https://github.com/DependencyTrack/hyades/issues/1175

Setup GitHub issue and PR templates

---

vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdx.java

De-duplicates Snyk vulnerabilities by ID.
This is a follow-up to https://github.com/DependencyTrack/hyades/pull/1168, where we added de-duplication based on the entire content of the vulnerability object.
Apparently that was not enough, as we're still getting duplicate vulns.
N/A
N/A

De-duplicate Snyk vulnerabilities by ID

---

monitoring/grafana/dashboards/apiserver_dashboard.json

> [!WARNING]
> Depends on https://github.com/DependencyTrack/hyades-apiserver/pull/554

Update API server dashboard to include Parallel Consumer metric for repo meta processing duration

---

notification-publisher/pom.xml
pom.xml

Bumps `kafka-clients` to 3.6.2 and removes `mockserver-netty`.
N/A
N/A

Bump `kafka-clients` to 3.6.2 and remove `mockserver-netty`

---

docker-compose.yml
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
mirror-service/src/main/resources/application.properties
notification-publisher/src/main/resources/application.properties
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Bumps versions of container images used in tests and the Compose demo setup.
N/A
N/A

Bump images

---

scripts/config-docs.md.peb

Removes generation timestamp from config documentation template.
SURPRISINGLY, including a timestamp will cause a change every time the generation script is invoked (https://github.com/DependencyTrack/hyades/pull/1197#issuecomment-2059282286).
Relates to #1154 
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/hyades/tree …

Remove timestamp from config doc template

---

docs/reference/configuration/mirror-service.md
mirror-service/src/main/resources/application.properties
mkdocs.yml

Enriches mirror-service `application.properties` with annotations for docs generation.
Relates to #1154
N/A

Enrich mirror-service configuration with annotations for docs generation

---

.github/workflows/deploy-docs.yml

Aliases docs for `-SNAPSHOT` versions as `snapshot`.
This will make the current unstable version's documentation available at https://dependencytrack.github.io/hyades/snapshot
N/A
N/A

Alias docs for `-SNAPSHOT` versions as `snapshot`

---

docs/operations/database.md

Uses hyperlinks when referring to configuration options in the docs.
N/A
N/A

Use hyperlinks when referring to configuration options in the docs

---

.github/release.yml
.github/workflows/update-config-docs.yml

Update labels used in workflows and release notes

---

mirror-service/pom.xml
notification-publisher/pom.xml
pom.xml
repository-meta-analyzer/pom.xml
vulnerability-analyzer/pom.xml

It was pointed out that the `groupId` of our `quarkus-maven-plugin` declarations are not in line with the other dependencies and plugins we use. For consistency's sake, it's now changed to `io.quarkus`.
Further, for some reason we added `quarkus-container-image-docker` as a Maven plugin, when in reality it is supposed to be used as a normal dependency.
N/A
N/A
- ~This PR introduces new or alters …

POM cleanup

---

.checkstyle.xml
pom.xml

Fixes:
```
Failed during checkstyle configuration: cannot initialize module Header - illegal value '.checkstyle-header' for property 'headerFile': com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: .checkstyle-header
```
When running a specific module (e.g. `vulnerability-analyzer`) via `mvn quarkus:dev`.
N/A
N/A
- ~This PR introduces new or alters existing behavior, and I have …

Fix Checkstyle error when running specific Maven module

---

docker-compose.yml
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
mirror-service/src/main/resources/application.properties
notification-publisher/src/main/resources/application.properties
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Bumps the Redpanda containers to the latest available version.
N/A
N/A

Bump Redpanda containers

---

e2e/src/main/java/org/dependencytrack/apiserver/ApiServerClient.java
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
e2e/src/test/java/org/dependencytrack/e2e/BomUploadProcessingE2ET.java
notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java

Fixes the failing `BomUploadProcessingE2ET` e2e test.
Email configuration is pulled from the database as of #1229. The e2e test still assumed configuration via properties.
Relates to #1229
N/A

Fix broken email notifications in e2e test

---

mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdx.java
vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdx.java

Fixes parsing of decimal numbers in non-English locales.
`NumberFormat#getInstance` uses the system's default locale per default to determine the digit separator.
This works fine if the system is English (where the separator is `.`), but breaks on e.g. a German one (where the separator is `,`).
Explicitly set the locale to `US` to resolve this.
N/A
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/hyades/tree/ …

Fix parsing of decimal numbers in non-English locales

---

.github/workflows/ci.yml

Fixes `Publish test coverage` build step which was missed in #1235.
N/A
N/A

Fix `Publish test coverage` build step

---

.github/workflows/ci.yml

Fixes `Commit SHA-1 hash isn't valid` when publishing coverage.
The variable passed to `--commit-uuid` does not exist for CI builds of the `main` branch. Use `github.sha` instead (see https://docs.github.com/en/actions/learn-github-actions/contexts for reference).
Relates to #1203
N/A

Fix `Commit SHA-1 hash isn't valid` when publishing coverage

---

docs/operations/database.md
docs/reference/configuration/api-server.md
docs/reference/configuration/mirror-service.md
scripts/config-docs.md.peb

Fixes minor documentation issues.
N/A
N/A

Minor doc fixes

---

pom.xml

Removes Sonar properties from `pom.xml`.
Relates to #1203
N/A

Remove Sonar properties

---

mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
pom.xml
repository-meta-analyzer/pom.xml
vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdx.java
vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/VulnerabilityAnalyzerIT.java
vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdxTest.java

Bumps `cvss-calculator` to `1.4.3`.
N/A
Also resolves an inconsistency where the GitHub API library's version was not managed by the parent POM.

Bump `cvss-calculator` to `1.4.3`

---

.github/workflows/update-config-docs.yml
docs/reference/configuration/repo-meta-analyzer.md
mirror-service/src/main/resources/application.properties
mkdocs.yml
repository-meta-analyzer/src/main/resources/application.properties

Enriches repo-meta-analyzer configuration with annotations for docs generation.
Relates to https://github.com/DependencyTrack/hyades/issues/1154
N/A

Enrich repo-meta-analyzer configuration with annotations for docs generation

---

commons-persistence/src/main/resources/schema.sql

Relates to change of check constraint in https://github.com/DependencyTrack/hyades-apiserver/pull/690
Closes https://github.com/DependencyTrack/hyades/issues/1256
~~- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective~~
~~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/hyades/tree/main/docs) accordingly~~

Update schema for clone project workflow

---

proto/src/main/proto/org/dependencytrack/notification/v1/notification.proto

This sync changes made to the proto in https://github.com/DependencyTrack/hyades-apiserver/pull/696
N/A
N/A

Add CVSS and OWASP vectors to notification proto

---

e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java

Fixes `VulnerabilityPolicyE2ET`.
The `operationMode` field in vulnerability policies is mandatory as of https://github.com/DependencyTrack/hyades-apiserver/pull/669.
N/A
N/A

Fix `VulnerabilityPolicyE2ET`

---

mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubMirror.java
mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubMirrorTest.java
mirror-service/src/test/resources/datasource/github/advisory-withdrawn.json

Ignore withdrawn Github advisories.
Backport changes https://github.com/DependencyTrack/hyades/issues/1190

Port: withdrawn check for github advisory

---

docs/operations/database.md
mkdocs.yml

Adds docs for advanced database configuration.
Relates to #928 
N/A

Add docs for advanced database config

---

docker-compose.yml
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
mirror-service/src/main/resources/application.properties
notification-publisher/src/main/resources/application.properties
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Bumps Redpanda to v24.1.7.
Bump Redpanda Console to v2.6.0.
N/A
N/A

Bump Redpanda and Redpanda Console

---

docker-compose.yml

Fixes `role "root" does not exist` warning logs in postgres, caused by incorrect health check in `docker-compose.yml`.
Relates to https://github.com/DependencyTrack/hyades/issues/1320
https://stackoverflow.com/questions/60193781/postgres-with-docker-compose-gives-fatal-role-root-does-not-exist-error

Fix `role "root" does not exist` in postgres healthcheck

---

commons/src/main/java/org/dependencytrack/common/cwe/CweDictionary.java

Ports https://github.com/DependencyTrack/dependency-track/pull/3491 from Dependency-Track v4.11.0
Command used:
```
jbang gen-cwe-dict@DependencyTrack -v 4.13 -p 'org.dependencytrack.common.cwe' -o commons/src/main/java/org/dependencytrack/common/cwe/CweDictionary.java --jakarta
```
Relates to #1190 
N/A

Port: Bump CWE dictionary to v4.13

---

README.md

Updates *Deployment* docs for Helm chart.
Relates to #1226 
N/A

Update Deployment docs for Helm chart

---

.github/workflows/ci.yml
.github/workflows/release.yml

Ports https://github.com/DependencyTrack/dependency-track/pull/3677 from Dependency-Track v4.11.0.
Relates to #1190 
N/A

Port: Disable Maven transfer progress in CI

---

.gitignore
commons-persistence/src/main/java/org/dependencytrack/persistence/model/RepositoryType.java
repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/HackageMetaAnalyzer.java
repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/NixpkgsMetaAnalyzer.java
repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/HackageMetaAnalyzerTest.java
repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NixpkgsMetaAnalyzerTest.java

Implement the hackage and nixpkgs meta analyzers
Backport change https://github.com/DependencyTrack/hyades/issues/1190

Port: add hackage and nixpkgs analyzers

---

.github/PULL_REQUEST_TEMPLATE.md

Links to docs for DB migration and doc update checkboxes in the PR template.
Instead of linking to the raw sources, link to the documentation that explains how to work on them.
N/A
N/A

Link to docs for DB migration and doc update checkboxes

---

README.md

Updates the port status in `README.md`.
It still refers to v4.9.1, but now we catched up to v4.11.3!
Relates to #1190 
N/A

Update port status in `README.md`

---

.github/workflows/deploy-docs.yml
.gitignore
mkdocs.yml

Enables social cards for documentation.
This merely enables them with default settings.
Might want to customize them in the future: <https://squidfunk.github.io/mkdocs-material/tutorials/social/basic/>
N/A
N/A …

Enable social cards for documentation

---

.github/workflows/update-proto-docs.yml
docs/reference/schemas/notification.md
docs/reference/schemas/notification.md.tmpl
docs/reference/schemas/policy.md
docs/reference/schemas/policy.md.tmpl
mkdocs.yml
proto/src/main/proto/org/dependencytrack/policy/v1/policy.proto
scripts/gen-proto-docs.sh

Adds basic documentation for `policy.proto` and `notification.proto` and makes them available under *Reference* -> *Schemas* in the docs site.
This is useful to link to the definitions from other areas in the docs.
A GitHub Actions workflow to update the docs automatically when the `.proto` files change is included.
N/A
N/A …

Generate documentation for Protobuf definitions

---

mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParserTest.java
vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdx.java
vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdx.java
vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdxTest.java
vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdxTest.java

Gracefully handles `MalformedVectorException`s for invalid CVSS vectors.
Some sources like OSS Index have started to report CVSSv4 vectors, which we / the `cvss-parser` library do not currently support.
Ensure that parsing of CVSS vectors is done with the possibility of invalid vectors in mind.
N/A
N/A …

Gracefully handle `MalformedVectorException`s for invalid CVSS vectors

---

docker-compose.yml
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
mirror-service/src/main/resources/application.properties
notification-publisher/src/main/resources/application.properties
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Bumps Redpanda to v24.1.11.
N/A
<https://github.com/redpanda-data/redpanda/releases/tag/v24.1.11>

Bump Redpanda to v24.1.11

---

.github/release.yml

Adds a *breaking changes* category to release notes.
N/A
N/A

Add breaking changes category to release notes

---

docker-compose.yml
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
mirror-service/src/main/resources/application.properties
notification-publisher/src/main/resources/application.properties
pom.xml
repository-meta-analyzer/pom.xml
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Updates various dependencies that Dependabot has not picked up.
N/A
N/A

Update various dependencies

---

.mvn/maven.config

Enable Quarkus incubating model resolver.
As per https://quarkus.io/blog/incubating-model-resolver/
N/A
N/A

Enable Quarkus incubating model resolver

---

docker-compose.yml
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
mirror-service/src/main/resources/application.properties
notification-publisher/src/main/resources/application.properties
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Bumps Redpanda to v24.2.2.
This addresses https://support.redpanda.com/hc/en-us/articles/25483263551383-TSB-2024-11-Avoid-installing-or-upgrading-to-Redpanda-v24-2-1-and-instead-directly-go-to-Redpanda-v24-2-2.
Redpanda has removed the v24.2.1 release, which currently causes build failures for us because the image can't be pulled.
N/A
N/A
[contributing guidelines]: …

Bump Redpanda to v24.2.2

---

commons/src/main/java/org/dependencytrack/common/cwe/CweDictionary.java

Ports https://github.com/DependencyTrack/dependency-track/pull/3819 from Dependency-Track v4.12.0-SNAPSHOT.
Relates to https://github.com/DependencyTrack/hyades/issues/1358
N/A

Port: Bump CWE dictionary to v4.14

---

docs/development/building.md

Adds build instructions to development docs.
N/A
N/A

Add build instructions to development docs

---

docs/getting-started/upgrading.md
mkdocs.yml

Adds upgrade notes.
While we do label breaking changes in pull requests and issues, we can't expect users to sift through all of them to determine whether any action is needed upon upgrading to a newer version.
This adds a new Upgrading page to the documentation, which will list notable and breaking changes for each version.
N/A
N/A
[contributing guidelines]: …

Add upgrade notes

---

mkdocs.yml

Integrate table-of-contents into navigation bar for more content space on the documentation page.
N/A
Before:
After:

Docs: integrate TOC into navigation bar for more content space

---

docker-compose.yml

Disables database connection pooling for initializer.
The initializer executes queries sequentially and does not benefit from pooling. Avoid the overhead of creating many useless connections.
N/A
N/A

Disable database connection pooling for initializer

---

.github/workflows/release.yml
mirror-service/pom.xml
notification-publisher/pom.xml
pom.xml
repository-meta-analyzer/pom.xml
vulnerability-analyzer/pom.xml

Migrates to Quarkus-native CycloneDX SBOM generation.
N/A
We generate and publish SBOMs for the [Fast JAR](https://quarkus.io/guides/cyclonedx#fast-jar) distribution of our applications.

Migrate to Quarkus-native CycloneDX SBOM generation

---

docs/getting-started/upgrading.md

Adds upgrade note for Kafka processor property name change.
Relates to https://github.com/DependencyTrack/hyades-apiserver/pull/904
N/A …

Add upgrade note for Kafka processor property name change

---

commons-persistence/src/main/java/org/dependencytrack/persistence/model/Vulnerability.java
docs/getting-started/changes-over-v4.md
docs/getting-started/upgrading.md

Remove deprecated code and document the endpoints removed in apiserver.
https://github.com/DependencyTrack/hyades/issues/1428

Remove deprecated code + update documentation

---

.github/workflows/e2e-test.yml

Fixes scheduled e2e tests failing due to missing image tag.
The inputs defined on `workflow_dispatch` won't ever be set when the workflow is triggered on schedule. Hence, we default to `snapshot` now.
N/A
N/A

Fix scheduled e2e tests failing due to missing image tag

---

e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java

Adds initializer container to e2e tests.
N/A
N/A

Add initializer container to e2e tests

---

docker-compose.yml
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
mirror-service/src/main/resources/application.properties
notification-publisher/src/main/resources/application.properties
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Bumps various containers tags to more recent versions.
N/A
N/A

Bump various containers tags

---

mirror-service/pom.xml
mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubApiClientFactory.java
mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubHttpRequestRetryStrategy.java
mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubMirror.java
mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubReflectionConfiguration.java
mirror-service/src/test/java/org/dependencytrack/vulnmirror/KafkaStreamsTopologyIT.java
mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubHttpRequestRetryStrategyTest.java
mirror-service/src/test/resources/datasource/github/advisories-page-01.json
mirror-service/src/test/resources/datasource/github/advisories-page-02.json
mirror-service/src/test/resources/datasource/github/advisory-02.json
mirror-service/src/test/resources/datasource/github/advisory-withdrawn.json
mirror-service/src/test/resources/datasource/github/advisory.json
pom.xml

Handles GitHub GraphQL API rate limiting.
Ports https://github.com/DependencyTrack/dependency-track/pull/4578
Related to https://github.com/DependencyTrack/hyades/issues/1358
N/A

Port: Handle GitHub GraphQL API rate limiting

---

.github/workflows/_build-native-meta.yml

Uses native ARM runner to build arm64 native images.
N/A
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/ …

Use native ARM runner to build arm64 native images

---

.github/workflows/_build-native-meta.yml

Removes buildx from native image build job.
Buildx is not available on the arm64 platform, and also no longer necessary because we don't do cross-compilation anymore.
N/A
N/A

Remove buildx from native image build job

---

docker-compose.yml
e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
mirror-service/src/main/resources/application.properties
notification-publisher/src/main/resources/application.properties
repository-meta-analyzer/src/main/resources/application.properties
vulnerability-analyzer/src/main/resources/application.properties

Bumps container image versions.
N/A
N/A

Bump container image versions

---

.github/workflows/_build-native-meta.yml
.github/workflows/mirror-container-image.yml
.github/workflows/publishJar.yml
.github/workflows/release.yml

Mirrors container images to Docker Hub.
~Still to be done: Images must be pushed to ghcr.io using a personal access token. Pushing images using the default `secrets.GITHUB_TOKEN` will not trigger other workflows.~
N/A
N/A

Mirror container images to Docker Hub

---

docs/architecture/decisions/006-consolidate-user-tables.md
mkdocs.yml

Add ADR for consolidating user tables.
Relates to #1760
N/A

Add ADR for consolidating user tables

---

.github/workflows/update-config-docs.yml
docs/development/building.md
docs/development/testing.md

Updates path to API server config.
Relates to https://github.com/DependencyTrack/hyades/issues/1710
API Server PR: https://github.com/DependencyTrack/hyades-apiserver/pull/1121 …

Update path to API server config

---

docs/architecture/decisions/007-spec-first-rest-api-v2.md
mkdocs.yml

Adds ADR-007: Spec-First REST API v2.
N/A
N/A

Add ADR-007: Spec-First REST API v2

---

docker-compose.yml

Updates the `initializer` config in `docker-compose.yaml`.
Optimizes JVM flags for short-lived execution and explicitly configure database details for init tasks only.
N/A
N/A …

Update initializer config in `docker-compose.yaml`

---

commons-kstreams/src/main/java/org/dependencytrack/kstreams/processor/TombstoneEmittingProcessor.java

Enforces punctuation latency ceiling.
N/A
Refer to code comments.

Enforce punctuation latency ceiling

---

docs/architecture/decisions/010-vulnerability-datasource-extension-point.md
mkdocs.yml

Adds ADR for vuln data source extension point.
N/A
N/A

Add ADR for vuln data source extension point
